mongodb/mongo-csharp-driver

src/MongoDB.Driver/MongoIndexManagerBase.cs

added missing ConfigureAwait(false) call on CreateOneAsync impl

---

Docs/reference/content/reference/driver/error_handling.md
Docs/reference/content/reference/driver_core/events.md
src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs

- fixs the grammar of the word "occurred"

fix grammatical errors

---

tests/MongoDB.Driver.Core.Tests/Core/Operations/GeoSearchOperationTests.cs
tests/MongoDB.Driver.Legacy.Tests/MongoCollectionTests.cs

https://spruce.mongodb.com/version/5fb2da810305b934962e3a79/tasks

CSHARP-3249: Skip Geo Haystack tests on Latest Server

---

Docs/reference/content/reference/driver/crud/client_side_encryption.md

CSHARP-3300: Update FLE documentation to mention that it's currently supported on Linux and Mac.

---

src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
src/MongoDB.Driver/MongoDB.Driver.csproj
tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs

EG: https://evergreen.mongodb.com/version/601ae5615623432d4fa67c52

Update version of libmongocrypt.

---

tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp269Tests.cs

EG: https://evergreen.mongodb.com/version/602694b5c9ec443827786043

CSHARP-3423: Fix CSharp269Tests.TestUploadAndDownload GridFs test on sharded cluster.

---

Docs/reference/content/reference/driver/authentication.md

Documentation updates for GSSAPI support on Linux.

CSHARP-2474/CSHARP-2481 Added documentation for Kerberos/GSSAPI on Linux

---

README.md
src/MongoDB.Bson/MongoDB.Bson.csproj
src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
src/MongoDB.Driver.GridFS/MongoDB.Driver.GridFS.csproj
src/MongoDB.Driver.Legacy/MongoDB.Driver.Legacy.csproj
src/MongoDB.Driver/MongoDB.Driver.csproj

Updated authors list to MongoDB Inc.
Corrected the spelling on Mikalai's last name.
Updated maintainers list in README.md.
Updated project URL to point to new landing page.

CSHARP-3256: Updated authors list to MongoDB Inc. and fixed other project metadata

---

README.md
build.cake

This requires testing during our next release. If it doesn't work as expected, we may have to revert this change until we can investigate further.

CSHARP-3231: Push directly to nuget.org

---

src/MongoDB.Driver.Core/Core/Clusters/DnsMonitor.cs
tests/MongoDB.Driver.Core.Tests/Core/Clusters/MultiServerClusterTests.cs

[EG](https://evergreen.mongodb.com/version/6039578a3627e02361c18e30) (private link)

CSHARP-3429: Setting DNS monitoring thread as background thread

---

src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
src/MongoDB.Driver/MongoDB.Driver.csproj

EG: https://evergreen.mongodb.com/version/605284d6d1fe0731e8aa4eda

CSHARP-3489: Update libmongocrypt nuget reference on 1.2.1 version.

---

src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/OperationsCountServerSelector.cs
src/MongoDB.Driver.Core/Core/Misc/Feature.cs
src/MongoDB.Driver.Core/Core/Servers/IServer.cs
src/MongoDB.Driver.Core/Core/Servers/Server.cs
tests/MongoDB.Bson.TestHelpers/ThreadingUtilities.cs
tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/InWindowTestRunner.cs
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/ServerSelectionTestHelpers.cs
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/ServerSelectionTestRunner.cs
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/equilibrium.json
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/equilibrium.yml
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/many-choices.json
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/many-choices.yml
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/one-least-two-tied.json
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/one-least-two-tied.yml
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/rs-equilibrium.json
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/rs-equilibrium.yml
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/rs-three-choices.json
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/rs-three-choices.yml
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/three-choices.json
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/three-choices.yml
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/two-choices.json
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/two-choices.yml
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/two-least.json
tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/tests/in_window/two-least.yml
tests/MongoDB.Driver.Tests/ClusterTests.cs

[EG](https://evergreen.mongodb.com/version/60664f99e3c33117576b4303) (internal link)

CSHARP-3304: Consider server load during server selection

---

src/MongoDB.Bson/Serialization/BsonClassMap.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-2940
EG: https://evergreen.mongodb.com/version/607d8e9c57e85a62cdb149ed

CSHARP-2940: Check uses of FormatterServices when targetting netstandard2.0

---

src/MongoDB.Bson/Serialization/BsonSerializer.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-2942
EG: https://evergreen.mongodb.com/version/607f283530661503dcfb078f

CSHARP-2942: Check uses of GetCustomAttributes when targetting netstandard2.0

---

src/MongoDB.Shared/IncrementalMD5.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-2956
EG: https://evergreen.mongodb.com/version/608817ef3627e06f01825208

CSHARP-2956: Check IncrementalMDNet45 vs IncrementalMDNetStandard16 when targetting netstandard2.0

---

src/MongoDB.Driver.Core/Core/Connections/TcpStreamFactory.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-2946
EG: https://evergreen.mongodb.com/version/60917b575623430b33b5630f
Note: this PR just adds a sync version of `Dns.GetHostAddresses`, because it is available since netstandard 2.0. The swap in target paths (`#if NET452`) is made to avoid negative conditions (just as a general rule, nothing specific).

CSHARP-2946: Check uses of DNS methods when targetting netstandard2.0

---

src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-2951
EG: https://evergreen.mongodb.com/version/6091b9c23066152f70cd8d31

CSHARP-2951: Check ClientDocumentHelper CreateOSDocument method when targetting netstandard2.0

---

src/MongoDB.Driver.Core/Core/NativeLibraryLoader/LibraryLoader.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-2954
EG: https://evergreen.mongodb.com/version/6095596dd6d80a79b13ef3ab
CSHARP-2954

CSHARP-2954: Check LibraryLoader methods when targetting netstandard2.0

---

src/MongoDB.Driver/Encryption/MongocryptdFactory.cs
tests/MongoDB.Driver.Tests/MongocryptdFactoryTests.cs
tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs

EG: https://evergreen.mongodb.com/version/609bf7c05623435d54272bf4

CSHARP-3510: Update serverSelectionTimeoutMS of MongoClient to mongocryptd.

---

build.cake
build.config
evergreen/compile.sh
evergreen/run-atlas-connectivity-tests.sh
evergreen/run-atlas-data-lake-test.sh
evergreen/run-gssapi-auth-tests.sh
evergreen/run-mongodb-aws-test.sh
evergreen/run-plain-auth-tests.sh
evergreen/run-tests.sh
tools/packages.config

EG: https://evergreen.mongodb.com/version/609be9099ccd4e52639e23fb

CSHARP-3268: Update to Cake v1.1.0.

---

tests/MongoDB.Driver.Core.Tests/Core/Connections/BinaryConnectionTests.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-3694
EG:
1. https://evergreen.mongodb.com/version/60b159ac3e8e860bb9483486
2. https://evergreen.mongodb.com/version/60b15f2b850e61283ccb1f42
3. https://evergreen.mongodb.com/version/60b15f360305b9589f2969c4
4. https://evergreen.mongodb.com/version/60b15f4256234370cdbbfb99

CSHARP-3694: Sporadic tests failures: ReceiveMessage_should_not_produce_unobserved_task_exceptions_on_fail

---

tests/MongoDB.Driver.Examples/VersionedApiExamples.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-3658

CSHARP-3658: Versioned API Connection Examples for Docs

---

evergreen/evergreen.yml

JIRA: https://jira.mongodb.org/browse/CSHARP-3682
EG: https://evergreen.mongodb.com/version/60db4fe60ae606784226a96b

CSHARP-3682: Test against 5.0 servers

---

src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterDescriptionTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerDescriptionTests.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-3699
EG: https://evergreen.mongodb.com/version/60e644df3627e06703f955c2

CSHARP-3699: Bump maxWireVersion for MongoDB 5.0

---

build.cake
evergreen/evergreen.yml
evergreen/run-tests.sh
src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilderExtensions.cs
tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
tests/MongoDB.Driver.Core.Tests/Core/Operations/BulkMixedWriteOperationTests.cs
tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-is-enforced.json
tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-is-enforced.yml
tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-timeout.json
tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/tests/pool-checkout-maxConnecting-timeout.yml
tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/tests/pool-checkout-returned-connection-maxConnecting.json
tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/tests/pool-checkout-returned-connection-maxConnecting.yml
tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
tests/MongoDB.Driver.Tests/AsyncCursorTests.cs
tests/MongoDB.Driver.Tests/CustomServerSelectorTests.cs
tests/MongoDB.Driver.Tests/Linq/Translators/PredicateTranslatorValidationTests.cs
tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
tests/MongoDB.Driver.Tests/Specifications/command-monitoring/CommandMonitoringTestRunner.cs
tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs

JIRA: https://jira.mongodb.org/browse/CSHARP-3714
EG: https://evergreen.mongodb.com/version/60e63dec2a60ed546b45f97e

CSHARP-3714: Implement missing test from Versioned API specification

---

CSharpDriver.sln
src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
src/MongoDB.Driver/Encryption/ClientEncryption.cs
src/MongoDB.Driver/Encryption/EncryptOptions.cs
src/MongoDB.Driver/Encryption/EncryptionAlgorithm.cs
src/MongoDB.Driver/Encryption/ExplicitEncryptionLibMongoCryptController.cs
src/MongoDB.Driver/MongoDB.Driver.csproj
tests/MongoDB.Driver.Examples/ExplicitEncryptionExamples.cs
tests/MongoDB.Driver.Tests/EncryptOptionsTests.cs
tests/MongoDB.Driver.Tests/EncryptionTests.cs

NOTE: I launched tests only locally, let me know if I need to make it possible to launch all tests on EG before a new libmongocrypt will be pushed

CSHARP-3527: Consider accepting EncryptionAlgorithm enum in EncryptOptions.

---

build.cake
evergreen/evergreen.yml
tests/AstrolabeWorkloadExecutor/AstrolabeWorkloadExecutor.csproj
tests/AtlasConnectivity.Tests/AtlasConnectivity.Tests.csproj
tests/MongoDB.Bson.TestHelpers/MongoDB.Bson.TestHelpers.csproj
tests/MongoDB.Bson.Tests/MongoDB.Bson.Tests.csproj
tests/MongoDB.Driver.Core.TestHelpers/MongoDB.Driver.Core.TestHelpers.csproj
tests/MongoDB.Driver.Core.Tests/MongoDB.Driver.Core.Tests.csproj
tests/MongoDB.Driver.Examples/MongoDB.Driver.Examples.csproj
tests/MongoDB.Driver.GridFS.Tests/MongoDB.Driver.GridFS.Tests.csproj
tests/MongoDB.Driver.Legacy.TestHelpers/MongoDB.Driver.Legacy.TestHelpers.csproj
tests/MongoDB.Driver.Legacy.Tests/MongoDB.Driver.Legacy.Tests.csproj
tests/MongoDB.Driver.TestHelpers/MongoDB.Driver.TestHelpers.csproj
tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
tests/SkippableTests/SkippableTests.csproj

CSHARP-2661
Supersedes https://github.com/durran/mongo-csharp-driver/pull/7

CSHARP-2661: Show Test Results in Evergreen

---

tests/MongoDB.Driver.Legacy.Tests/Linq/SelectOfTypeHierarchicalTests.cs
tests/MongoDB.Driver.Legacy.Tests/Linq/SelectQueryTests.cs
tests/MongoDB.Driver.Tests/Linq/Translators/LegacyPredicateTranslatorTests.cs

Enable tests that were temporary disabled due a server bug

CSHARP-3704: Temporarily disable tests failing due to SERVER-57300.

---

src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs

AcquireConnection_should_iterate_over_all_dormant_connections timings tuning

CSHARP-3799: Fix flacky AcquireConnection_should_iterate_over_all_dormant_connections test

---

src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs

[EG](https://spruce.mongodb.com/version/6154a8810305b929712ef07d/tasks)

CSHARP-3884: Driver calls SemaphoreSlim.WaitAsync with negative timeout values

---

tests/MongoDB.Driver.Tests/Specifications/command-monitoring/tests/unified/pre-42-server-connection-id.json
tests/MongoDB.Driver.Tests/Specifications/command-monitoring/tests/unified/pre-42-server-connection-id.yml
tests/MongoDB.Driver.Tests/Specifications/command-monitoring/tests/unified/server-connection-id.json
tests/MongoDB.Driver.Tests/Specifications/command-monitoring/tests/unified/server-connection-id.yml
tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs

Just test related changes. The main part is already implemented before

CSHARP-3744: Add server connectionId to command monitoring events.

---

index.html

Preview: https://dmitrylukyanov.github.io/mongo-csharp-driver/

Set current version to 2.13.2.

---

Docs/landing/data/releases.toml
Release Notes/Release Notes v1.7.md
Release Notes/Release Notes v1.8.1.md
Release Notes/Release Notes v1.8.2.md
Release Notes/Release Notes v1.8.3.md
Release Notes/Release Notes v1.8.md
Release Notes/Release Notes v1.9.1.md
Release Notes/Release Notes v1.9.2.md
Release Notes/Release Notes v1.9.md
Release Notes/Release Notes v2.2.0.md

This PR is against master and is so that the links in future releases will be live.
Updating the gh-pages branch is a separate task.

CSHARP-4009: Replace dead links to api.mongodb.org with valid links.

---

Docs/reference/content/reference/driver/ssl.md

Summarized TLS cipher suite mismatch troubleshooting information from CSHARP-3564.

CSHARP-3564: Added TLS cipher suite mismatch troubleshooting to the docs

---

Docs/reference/content/getting_started/quick_tour.md

Fixed json format

---

src/MongoDB.Driver.Core/Core/Operations/AggregateOperation.cs
src/MongoDB.Driver.Core/Core/Operations/AsyncCursor.cs
src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
src/MongoDB.Driver.Core/Core/Operations/ListCollectionsOperation.cs
src/MongoDB.Driver.Core/Core/Operations/ListIndexesUsingCommandOperation.cs
src/MongoDB.Driver.Core/Core/Operations/ParallelScanOperation.cs
tests/MongoDB.Driver.Core.Tests/Core/Operations/AsyncCursorEnumeratorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Operations/AsyncCursorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Operations/CursorTests.cs
tests/MongoDB.Driver.Core.Tests/IAsyncCursorExtensionsTests.cs
tests/MongoDB.Driver.Core.Tests/IAsyncCursorSourceExtensionsTests.cs
tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams.json
tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams.yml
tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/aggregate.json
tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/aggregate.yml
tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/find-comment.json
tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/find-comment.yml

[EG](https://evergreen.mongodb.com/version/6216bf967742ae3d1fb501f1)
Done with [CSHARP-4078](https://jira.mongodb.org/browse/CSHARP-4078)

CSHARP-4046: getMore helper should explicitly send inherited comment

---

src/MongoDB.Driver.Core/Core/Misc/Feature.cs
tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4140Tests.cs

CSHARP-4140: Skip $getField tests on older servers.

---

src/MongoDB.Driver/IFindFluentExtensions.cs
tests/MongoDB.Driver.Tests/IFindFluentExtensionsTests.cs

[Jira Link](https://jira.mongodb.org/browse/CSHARP-4203)

CSHARP-4203: IFindFluentExtensions for Any and AnyAsync

---

tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2107Tests.cs

No changes to push to master.
Just verifying that the issue is no longer present.

CSHARP-2107: Verified that the issue is no longer present in LINQ3.

---

tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3614Tests.cs

No changes to push to master.
Just verify issue is no longer present.

CSHARP-3614: Verify issue is no longer present in LINQ3.

---

tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4057Tests.cs

No changes to push to master.
Just verifying that the issue is no longer present in LINQ3.

CSHARP-4057: Verify that issue is no longer present in LINQ3.

---

Docs/reference/content/reference/driver/crud/linq3.md

I was going to ask Dima for a review to spread the reviews around, but wanted Boris' feedback as well since I'm mentioning the Analyzer. Thanks in advance for double-checking my correctness and grammar.

CSHARP-4206: Update LINQ3 docs to note that the LINQ3 provider is production-ready.

---

tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4317Tests.cs

CSHARP-4317: Added integration test demonstrating that CSHARP-4316 fix also resolved dictionary key/value projection issue.

---

src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
tests/MongoDB.Driver.Core.Tests/Core/Bindings/CoreSessionTests.cs

EGs:
1. https://evergreen.mongodb.com/version/63252c6e2fbabe6dc475ca38
2. https://evergreen.mongodb.com/version/63252c9d3627e012c6ca4981
3. https://evergreen.mongodb.com/version/63252cbae3c331285526fb19
4. https://evergreen.mongodb.com/version/63252cd561837d6cce9b03cf

CSHARP-4326: Fix serverless tests.

---

CSharpDriver.sln
build.cake
build.ps1
build.sh
evergreen/evergreen.yml
tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/InfrastructureUtilities.cs
tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LogEntry.cs
tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LoggingTests.cs
tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LogsTraceListener.cs
tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/xunit.runner.json

[Smoke tests EG](https://spruce.mongodb.com/version/62e304fe3e8e865395b6ccd1)

CSHARP-4241: Basic smoke tests

---

specifications/command-logging-and-monitoring/tests/logging/command.json
specifications/command-logging-and-monitoring/tests/logging/command.yml
specifications/command-logging-and-monitoring/tests/logging/driver-connection-id.json
specifications/command-logging-and-monitoring/tests/logging/driver-connection-id.yml
specifications/command-logging-and-monitoring/tests/logging/no-handshake-messages.json
specifications/command-logging-and-monitoring/tests/logging/no-handshake-messages.yml
specifications/command-logging-and-monitoring/tests/logging/no-heartbeat-messages.json
specifications/command-logging-and-monitoring/tests/logging/no-heartbeat-messages.yml
specifications/command-logging-and-monitoring/tests/logging/operation-id.json
specifications/command-logging-and-monitoring/tests/logging/operation-id.yml
specifications/command-logging-and-monitoring/tests/logging/pre-42-server-connection-id.json
specifications/command-logging-and-monitoring/tests/logging/pre-42-server-connection-id.yml
specifications/command-logging-and-monitoring/tests/logging/redacted-commands.json
specifications/command-logging-and-monitoring/tests/logging/redacted-commands.yml
specifications/command-logging-and-monitoring/tests/logging/server-connection-id.json
specifications/command-logging-and-monitoring/tests/logging/server-connection-id.yml
specifications/command-logging-and-monitoring/tests/logging/service-id.json
specifications/command-logging-and-monitoring/tests/logging/service-id.yml
tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs

CSHARP-4346: Add log messages to Command monitoring spec

---

build.cake

Removed the Test task and ensured that our release process doc calls out ensuring that Evergreen is green. Asking for everyone's LGTM just in case I missed something else that should be updated.

CSHARP-4388: Removed Test task from Release task.

---

src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj

Reverts mongodb/mongo-csharp-driver#981

Revert "CSHARP-4442: Hide aws sdk in release package."

---

src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MemberInitExpressionToAggregationExpressionTranslator.cs
tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToAggregationExpressionTranslators/MemberInitExpressionToAggregationExpressionTranslatorTests.cs

Please note this PR is to be followed by another, that will actually remove all code related to new expression translation, by calling init expression translator.

CSHARP-4550: NewExpression and MemberInitExpression behaviour differs

---

src/Directory.Build.props

Fixed the nuspec file that I borked.

CSHARP-4667: Updated the nuspec reference to LICENSE.md.

---

CODEOWNERS

Simple change that will allow us to set up automated PR review assignments.

CSHARP-4750: Added global CODEOWNERS file.

---

tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
tests/MongoDB.Driver.Tests/Specifications/retryable-reads/RetryableReadsTestRunner.cs
tests/MongoDB.Driver.Tests/Specifications/retryable-writes/RetryableWriteTestRunner.cs

Enabling tracked in CSHARP-4761

CSHARP-4760: Temporary disable serverless tests with failpoints

---

src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
src/MongoDB.Driver.Core/Core/Connections/HelloHelper.cs
src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoAWSAuthenticatorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBX509AuthenticatorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Authentication/PlainAuthenticatorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha256AuthenticatorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionInitializerTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Connections/HelloHelperTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Servers/RoundTripTimeMonitorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
tests/MongoDB.Driver.Core.Tests/Core/WireProtocol/CommandWriteProtocolTests.cs
tests/MongoDB.Driver.Core.Tests/Jira/CSharp3173Tests.cs

Ensures that if load balancing is enabled, both 'hello' and OP_MSG are used for the connection handshake.

CSHARP-4018: Require hello_command + OP_MSG when loadBalanced=true

---

src/MongoDB.Driver/ProjectionDefinitionBuilder.cs
tests/MongoDB.Driver.Tests/ProjectionDefinitionBuilderTests.cs
tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
tests/MongoDB.Driver.Tests/Search/ProjectionDefinitionBuilderTests.cs

Also added typed field expression overloads  for Score* helpers

CSHARP-4939: Add VectorSearchScore builder for $vectorSearch stage

---

src/MongoDB.Driver.Core/Core/Operations/RetryabilityHelper.cs
src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
tests/MongoDB.Driver.Core.Tests/Core/Operations/RetryabilityHelperTests.cs

I tested locally against 4.2.24 sharded. Let's see if all the variants pass on the patch build.

CSHARP-4827: Fix an issue with pre 4.4 servers.

---

CSharpDriver.sln.DotSettings

Added solution-level layer contains following customization:
- Live code templates for standard Equals implementation (based on #1273)
- File header template

Add solution DotSettings file

---

src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
tests/MongoDB.Driver.Core.TestHelpers/DisposableEnvironmentVariable.cs
tests/MongoDB.Driver.Core.Tests/Core/Connections/ClientDocumentHelperTests.cs
tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
tests/MongoDB.Driver.Tests/ClientDocumentHelperTests.cs

Reverts mongodb/mongo-csharp-driver#1305

Revert "CSHARP-5021: Replace use of DisposableEnvironmentVariable with EnvironmentVariableProvider"

---

src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs

Properly dispose of classes implementing IDisposable in areas flagged as high impact issues in Coverity.

CSHARP-5069: Properly dispose of classes implementing IDisposable

---

tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs

The issue is reproducible on replica set environments because of race condition between replication and executing $out aggregation on secondary node.

CSHARP-4017: Fix flaky Aggregate_with__out_includes_read_preference_for_5.0__server error

---

evergreen/evergreen.yml

Add missing expansions for serverless tests

CSHARP-5244: Fix failing Serverless tests

---

tests/MongoDB.Driver.Tests/Specifications/auth/OidcAuthenticationProseTests.cs

The issue itself was fixed in scope of AWS separation/Auth refactoring PR. This PR is to add the new test to verify the fix.

CSHARP-5239: Clarify Reauthentication and Speculative Authentication combination behavior

---

src/MongoDB.Bson/IO/BsonBinaryReader.cs
src/MongoDB.Bson/IO/BsonReader.cs
src/MongoDB.Bson/IO/BsonWriter.cs
src/MongoDB.Bson/IO/IBsonReader.cs
src/MongoDB.Bson/IO/IBsonWriter.cs
src/MongoDB.Bson/IO/JsonReader.cs
src/MongoDB.Bson/IO/JsonWriter.cs
src/MongoDB.Bson/IO/WrappingBsonWriter.cs
src/MongoDB.Bson/Serialization/Serializers/GuidSerializer.cs
tests/MongoDB.Bson.Tests/IO/BsonBinaryReaderTests.cs
tests/MongoDB.Bson.Tests/IO/BsonBinaryWriterTests.cs
tests/MongoDB.Bson.Tests/IO/BsonDocumentWriterTests.cs
tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
tests/MongoDB.Bson.Tests/IO/JsonWriterTests.cs
tests/MongoDB.Bson.Tests/Serialization/Serializers/GuidSerializerTests.cs

I probably should write more tests, particularly for failing scenarios.
But I wanted to get an initial review of this and pivot to working on discriminators for EF for a while.

CSHARP-5269: Add ReadGuid and WriteGuid to BSON readers and writers.

---

src/MongoDB.Driver/Core/Servers/ServerMonitor.cs
tests/MongoDB.Driver.Tests/Core/Servers/ServerMonitorTests.cs

`ServerMonitor._heartbeatCancellationTokenSource` concurrent disposal

CSHARP-5361: Coverity analysis defect 162231

---

src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToPipelineTranslators/GroupJoinMethodToPipelineTranslator.cs

I have researched this and I think we are already generating the best possible MQL.
While looking at the translator though I did see a few refactorings I wanted to do.

CSHARP-5357: Refactor GroupJoin translator.
