- src/MongoDB.Driver.GridFS.Tests/GridFSDownloadStreamBaseTests.cs
- src/MongoDB.Driver.GridFS/GridFSSeekableDownloadStream.cs
Some potential fixes for seekable download stream.
- Checking for _chunk == null before starting.
- added logic for cacluating the the last chunk number.
https://jira.mongodb.org/browse/CSHARP-1489
> Fix for NullReferenceException for seekable download stream:

- src/MongoDB.Driver/MongoDatabaseImpl.cs
`CreateCollectionAsync` returns a `Task` in these cases.
I guess when creating the sync version the return was dropped as there's no longer anything to return.
This causes a `NullReferenceException` when `options == null`
> Bugfix CreateCollection doesn't return and throws NullReferenceException

- src/MongoDB.Driver/SslSettings.cs
- tests/MongoDB.Driver.Tests/SslSettingsTests.cs
Remove cloning of the certificates, as this was problematic as the private key is not included in the RawData of a cert and a cert cannot always be cloned in a deep manner (if it is non exportable)
> CSHARP-1914 Remove cloning of the certificates

- Release Notes/Release Notes v2.5.0.md
As part of https://jira.mongodb.org/browse/DRIVERS-407, support for server versions below 2.6 was removed in https://github.com/mongodb/mongo-csharp-driver/commit/c1f4e87edb410862f87976231bb0aac58de09856. 
I thought it might be helpful to also add this to the release notes, as it seems to be a breaking change.
> Removing support for MongoDB 2.6 in v2.5 release notes

- Docs/reference/content/getting_started/admin_quick_tour.md
The examples of RunCommand usage don't work correctly. I added the missing generic BsonDocument parameter.
> [Documentation] Fix for examples of RunCommand in Admin Quick Tour

- src/MongoDB.Bson/IO/JsonReader.cs
- tests/MongoDB.Bson.Tests/Specifications/bson-corpus/tests/binary.json
- tests/MongoDB.Bson.Tests/Specifications/bson-corpus/tests/bsonview
EG: https://evergreen.mongodb.com/version/601d956b3e8e86586c978855
> CSHARP-3355: Add more spec tests for invalid relaxed UUIDs.

- evergreen/evergreen.yml
- evergreen/set-temp-fle-aws-creds.sh
- evergreen/set-virtualenv.sh
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/README.rst
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/awsTemporary.json
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/awsTemporary.yml
EG:  https://evergreen.mongodb.com/version/60267f001e2d17709ece1633
> CSHARP-3371: Support AWS authentication with temporary credentials in CSFLE.

- Docs/README.md
Changed java docs to XML docs.
> CSHARP-3244: Corrected wording to refer to XML docs

- src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
- tests/MongoDB.Driver.Core.Tests/MongoDB.Driver.Core.Tests.csproj
Pulling in fix for DnsClient.NET issue #79. See CSHARP-3430 for details. 
Note that DnsClient.NET 1.4.0 depends on System.Buffers 4.5.1 forcing us to upgrade that as well.
> Update DnsClient.NET to 1.4.0 to resolve Kubernetes DNS failures

- tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
Select single server in Monitor_sleep_at_least_minHeartbeatFreqencyMS_between_checks test (test fails on connections strings containing multiple servers)
[EG](https://evergreen.mongodb.com/version/6039742061837d59d55e0d7a) (Internal link)
> CSHARP-3303: Fix Monitor_sleep_at_least_minHeartbeatFreqencyMS test on replica sets

- Docs/reference/content/reference/driver/connecting.md
- Docs/reference/content/reference/driver/versioned_api.md
JIRA: https://jira.mongodb.org/browse/CSHARP-3370
Connecting page: https://mikalaimazurenka.github.io/mongo-csharp-driver/2.12/reference/driver/connecting/
Versioned API page: https://mikalaimazurenka.github.io/mongo-csharp-driver/2.12/reference/driver/versioned_api/
> CSHARP-3370: Document Versioned API Usage in Drivers

- src/MongoDB.Driver.Core/Core/Misc/Feature.cs
- src/MongoDB.Driver.Core/Core/Misc/SemanticVersion.cs
- src/MongoDB.Driver.Core/Core/Operations/CountOperation.cs
- src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
- src/MongoDB.Driver/MongoCollectionImpl.cs
- tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
- tests/MongoDB.Driver.Core.Tests/Core/Operations/EstimatedDocumentCountOperationTests.cs
- tests/MongoDB.Driver.Tests/MongoCollectionImplTests.cs
- tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/crud/CrudUnifiedTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/README.rst
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/estimatedDocumentCount.json
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/estimatedDocumentCount.yml
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/tests/estimatedDocumentCount-4.9.json
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/tests/estimatedDocumentCount-4.9.yml
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/tests/estimatedDocumentCount-pre4.9.json
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/tests/estimatedDocumentCount-pre4.9.yml
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/tests/estimatedDocumentCount-serverErrors-4.9.json
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/tests/estimatedDocumentCount-serverErrors-4.9.yml
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/tests/estimatedDocumentCount-serverErrors-pre4.9.json
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/tests/estimatedDocumentCount-serverErrors-pre4.9.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1-strict.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1-strict.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1.yml
- tests/MongoDB.Driver.Tests/Specifications/wireversion-featurelist.rst
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEstimatedDocumentCountOperation.cs
EG: https://evergreen.mongodb.com/version/603d9a267742ae71684b20ab
> CSHARP-3422: Change estimatedDocumentCount() to use the $collStats Agg Stage Instead of Count Command.

- Docs/reference/content/reference/driver/crud/client_side_encryption.md
Only docs changes.
I restored changes from CSHARP-3300: https://github.com/mongodb/mongo-csharp-driver/pull/450/files#diff-525914cfce0449efb9693ca2513ce901aa04b611f50f800f2e42748fb922ecdfL24 with changed wording.
> CSHARP-3448: Update FLE documentation to mention that we currently don't support arm architecture.

- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1-strict.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1-strict.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/runcommand-helper-no-api-version-declared.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/runcommand-helper-no-api-version-declared.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/test-commands-deprecation-errors.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/test-commands-deprecation-errors.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/test-commands-strict-mode.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/test-commands-strict-mode.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/transaction-handling.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/transaction-handling.yml
EG: https://evergreen.mongodb.com/version/605a6221d6d80a3b8215e707
Only Json tests changes
> CSHARP-3450: Versioned API database aggregation test only works on 49+ servers.

- src/MongoDB.Bson/Serialization/BsonSerializer.cs
CSHARP-2450: Improved deserialization performance by switching from `HashSet<T>` protected by a `ReaderWriterLockSlim` to a `ConcurrentDictionary<K,V>` outside the `ReaderWriterLockSlim`.
The following PR is based heavily on work done by @dnickless in PR#433. I analyzed his changes to determine the origin of the observed 5-10% performance improvement and realized that it was not due to a change in data structure for the registration check but due to reduced locking in the hot deserialization path, notably `StandardDiscriminatorConvention.GetActualType`, which calls `BsonSerializer.EnsureKnownTypesAreRegistered`. By changing `__typesWithRegisteredKnownTypes` to a `ConcurrentDictionary<Type, Type>` (instead of a `HashSet<Type>`), I was able to move the registration check outside the …
> CSHARP-2450: Reduce locking costs in BsonSerializer

- tests/MongoDB.Driver.Core.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringTestRunner.cs
- tests/MongoDB.Driver.Core.Tests/Specifications/server-discovery-and-monitoring/tests/errors/write_errors_ignored.json
- tests/MongoDB.Driver.Core.Tests/Specifications/server-discovery-and-monitoring/tests/errors/write_errors_ignored.yml
JIRA: https://jira.mongodb.org/browse/CSHARP-3384
EG: https://evergreen.mongodb.com/version/6063856b3e8e861ac9faf89c
Specification: https://github.com/mongodb/specifications/commit/849adad42df1f7b0a4f56a53bb07a431c859ce26
Note: I reused the same test runner change from https://github.com/mongodb/mongo-csharp-driver/pull/483 PR, which assumes that `ExceptionMapper.MapNotPrimaryOrNodeIsRecovering` is able to return no exception.
> CSHARP-3384: Define error handling behavior of writeErrors and writeConcernError on Mongos

- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/README.rst
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/test-commands-deprecation-errors.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/test-commands-deprecation-errors.yml
JIRA: https://jira.mongodb.org/browse/CSHARP-3567
EG: https://evergreen.mongodb.com/version/6076220a1e2d176bc70a1024
> CSHARP-3567: Replace usages of 'acceptAPIVersion2' with 'acceptApiVersion2'

- src/MongoDB.Bson/IO/BsonStreamAdapter.cs
- src/MongoDB.Driver.GridFS/DelegatingStream.cs
- tests/MongoDB.Bson.Tests/IO/BsonStreamAdapterTests.cs
- tests/MongoDB.Driver.GridFS.Tests/DelegatingStreamTests.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-2938
EG: https://evergreen.mongodb.com/version/6079a9c5562343543bf6c0cf
Note: I wasn't adding new overrides, just adjusting existing.
> CSHARP-2938: Refactor Stream subclasses when targeting netstandard2.0

- src/MongoDB.Bson/Serialization/BsonMemberMap.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-2941
EG: https://evergreen.mongodb.com/version/607dbad91e2d175c283b7219
> CSHARP-2941: Check uses of TypeCode.DBNull when targeting netstandard2.0

- src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-2950
EG: https://evergreen.mongodb.com/version/6086d7e53e8e864ec7ec05f2
> CSHARP-2950: Check BinaryConnection WrapExceptions for exceptions wrapped when targetting netstandard2.0

- src/MongoDB.Driver.Core/Core/Authentication/AuthenticationHelper.cs
- src/MongoDB.Driver.Core/Core/Authentication/ScramSha256Authenticator.cs
- src/MongoDB.Driver.Core/Core/Authentication/Sspi/AuthIdentity.cs
- src/MongoDB.Driver.Core/Core/Misc/DecryptedSecureString.cs
- src/MongoDB.Driver/DecryptedSecureString.cs
- src/MongoDB.Shared/SecureStringHelper.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-2943
EG: https://evergreen.mongodb.com/version/608051033627e05a49938919
> CSHARP-2943: Check uses of SecureString when targetting netstandard2.0

- src/MongoDB.Driver.Core/Core/Authentication/ScramSha1Authenticator.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-2949
EG: https://evergreen.mongodb.com/version/608873a5c9ec4430ccbe600c
Note: I am not sure if the occurrence here: [Vendored/Rfc2898DeriveBytes.cs:290](https://github.com/mongodb/mongo-csharp-driver/blob/7579652682b8440440bbe0bb380de275342c4757/src/MongoDB.Driver.Core/Core/Authentication/Vendored/Rfc2898DeriveBytes.cs#L290) should be updated. The current .NET Framework implementation uses `HMAC.Create(string algName)` which is not accessible in netstandard 1.5: [Rfc2898DeriveBytes.cs:102](https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/rfc2898derivebytes.cs,102), .NET 5 uses `new HMACSHA1`: [Rfc2898DeriveBytes.cs:248](https://github.com/dotnet/runtime/blob/9a905533d739564c14306ba3349fd7f7d3ebb834/src/libraries/Syste …
> CSHARP-2949: Check uses of new HMACSHA1 when targetting netstandard2.0

- src/MongoDB.Driver.Core/Core/Authentication/ScramSha1Authenticator.cs
- src/MongoDB.Driver.Core/Core/Authentication/ScramSha256Authenticator.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-3623
EG: https://evergreen.mongodb.com/version/608984a732f417577d8f9a3f
Note: the first version of netstandard to allow specifying hash algorithm in `Rfc2898DeriveBytes` is 2.1: [netstandard 2.1 -> Rfc2898DeriveBytes](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes.-ctor?view=netstandard-2.1#System_Security_Cryptography_Rfc2898DeriveBytes__ctor_System_String_System_Byte___System_Int32_System_Security_Cryptography_HashAlgorithmName_)
> CSHARP-3623: Check uses of Rfc2898DeriveBytes when targeting netstandard2.0

- tests/AstrolabeWorkloadExecutor/Program.cs
- tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamUnifiedTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/crud/CrudUnifiedTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatValidFailTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatValidPassTestRunner.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedErrorMatcher.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
EG: https://evergreen.mongodb.com/version/608889753e8e8678e0e2d8a7
> CSHARP-3523: Split the unified test runner into 2 classes.

- src/MongoDB.Driver.Core/Core/Authentication/Sspi/SecurityBufferDescriptor.cs
- src/MongoDB.Driver.Core/Core/Authentication/Sspi/SspiSecurityContext.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-2945
EG: https://evergreen.mongodb.com/version/6089b241c9ec443023b2395c
Note: [Marshal.SizeOf\<T\>()](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.sizeof?view=netframework-4.5.2#System_Runtime_InteropServices_Marshal_SizeOf__1) and [Marshal.PtrToStructure\<T\>()](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostructure?view=netframework-4.5.2#System_Runtime_InteropServices_Marshal_PtrToStructure__1_System_IntPtr_) are available for .NET 4.5.2.
The reason why these directives were still present is likely because they were not updated when target changed from .NET 4.5 to .NET 4.5.2 along with introducing multitargeting (and these overloads are not available for .NET …
> CSHARP-2945: Check uses of Marshal when targetting netstandard2.0

- src/MongoDB.Driver.Core/Core/Authentication/SaslPrepHelper.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/SaslPrepHelperTests.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-2948
EG: https://evergreen.mongodb.com/version/60915e4c2fbabe7f9e1adb09
> CSHARP-2948: Check uses of string.Normalize in SaslPrepHelper when targetting netstandard2.0

- src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
- tests/MongoDB.Bson.TestHelpers/XunitExtensions/ClassValuesAttribute.cs
- tests/MongoDB.Bson.TestHelpers/XunitExtensions/RandomSeedAttribute.cs
- tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
CSHARP-3380: Iterate over all connections on connection checkout in ConnectionPool
[EG](https://evergreen.mongodb.com/version/607dc1f2a4cf47318e9e3122) (internal link)
> CSHARP-3380: Iterate over all connections on connection checkout 

- src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-3656
EG: https://evergreen.mongodb.com/version/60993fc09ccd4e190cbb7f5f
> CSHARP-3656: Check uses of socket.BeginConnect in LibMongoCryptControllerBase

- src/MongoDB.Driver.Core/Core/Misc/Feature.cs
- src/MongoDB.Driver.Core/ServerErrorCode.cs
- tests/AstrolabeWorkloadExecutor/Program.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
Spec: https://github.com/mongodb/specifications/commit/1b4ce24071065b9c00263939dbb7e9524147c068#diff-f718c246f51e05b3731a7b03b176a0d4b0c381a9261810742d2677823f963f98R2638
> CSHARP-3534: Workarounds for killAllSessions in unified test runner.

- src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/BinaryConnectionTests.cs
JIRA: https://jira.mongodb.org/browse/CSHARP-3462
EG: https://evergreen.mongodb.com/version/608081e657e85a60d6a8b5f8
Note: This is leftover from [CSHARP-3102: Memory leak related to heartbeat when connecting to Atlas clusters](https://github.com/mongodb/mongo-csharp-driver/commit/a2303983c22639a114727ec3696cb667e7817b8b).
And the sync path (`BinaryConnection.ReceiveMessage`) did not produce an unhandled exception (or it is not raised in the event for some reason), but I included both paths in the unit test.
> CSHARP-3462: Unobserved task exception on connection failure raises its head again

- src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
- tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
The slaveOk URI option has been deprecated in favour of readPreference=secondaryPreferred since at least MongoDB 2.2. Many drivers (such as pymongo) have already removed it while others never implemented it because it predated the URI options spec.
> CSHARP-3655: Removed deprecated URI option slaveOk=true

- src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
- src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingQueryMessageWireProtocol.cs
- tests/MongoDB.Driver.Core.Tests/Core/WireProtocol/CommandWriteProtocolTests.cs
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1-strict.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1-strict.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/crud-api-version-1.yml
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/transaction-handling.json
- tests/MongoDB.Driver.Tests/Specifications/versioned-api/tests/transaction-handling.yml
JIRA: https://jira.mongodb.org/browse/CSHARP-3635
EG: https://evergreen.mongodb.com/version/60abec5d7742ae543a22b94b
Specification changes: https://github.com/mongodb/specifications/commit/5b892c4061026550f9b0754686a1e0f9783ff354#diff-d81feb8a94e1a811734074bde8dff007c7872dde8117e6ccdc06c6eedcce268d
> CSHARP-3635: Require passing Versioned API options to getMore and transaction-continuing commands

- src/MongoDB.Driver.Core/Core/NativeLibraryLoader/RelativeLibraryLocatorBase.cs
- tests/MongoDB.Driver.Core.Tests/Core/NativeLibraryLoader/NativeLibraryLoaderTests.cs
EG: https://evergreen.mongodb.com/version/609d8e0e61837d3a55f5a870
> CSHARP-3427: Can't make use of compression when application path contain space.

- tests/MongoDB.Driver.Core.Tests/Core/NativeLibraryLoader/NativeLibraryLoaderTests.cs
Evergreen: https://evergreen.mongodb.com/version/60b6a2611e2d173aca1bb5ae
> CSHARP-3427: Fix test.

- src/MongoDB.Bson/Serialization/Conventions/NamedIdMemberConvention.cs
- tests/MongoDB.Bson.Tests/Serialization/Conventions/IdMemberConventionsTests.cs
While having an `Id` property without a getter is an uncommon design choice, we actually throw a `NullReferenceException` in `NamedIdMemberConvention` rather than simply not returning the getter-less `Id` member. This prevents the use of other attributes or conventions to identify another property as the `_id`. For example the following classes will throw when attempting to serialize them:
```
[BsonNoId]
class Class1 {
public int Id { set {} }
}
class Class2 {
[BsonIgnore]
public int Id { set {} }
}
class Class2 {
[BsonIgnore]
public int Id { set {} }
[BsonId]
public int AnotherId { get; set; }
}
```
The added null check in `NamedIdMemberConvention` allows all of the above classes to be mapped.
> CSHARP-3703: Fix NullReferenceException when Id property has no getter.

- src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
- src/MongoDB.Driver.Core/Core/Connections/CommandEventHelper.cs
- src/MongoDB.Driver.Core/Core/Connections/ConnectionInitializer.cs
- src/MongoDB.Driver.Core/Core/Connections/HelloHelper.cs
- src/MongoDB.Driver.Core/Core/Connections/IsMasterResult.cs
- src/MongoDB.Driver.Core/Core/Misc/HelloCommand.cs
- src/MongoDB.Driver.Core/Core/Misc/OppressiveLanguageConstants.cs
- src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
- src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
- src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
- src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
- src/MongoDB.Driver.Core/Core/WireProtocol/Messages/CommandMessage.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoAWSAuthenticatorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBX509AuthenticatorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/PlainAuthenticatorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha256AuthenticatorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionInitializerTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/HelloHelperTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/IsMasterResultTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Servers/RoundTripTimeMonitorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
This implements using `hello` instead of `isMaster` when server API version is declared for both the initial handshake and monitoring.
NOTE: This PR does not add support for `helloOk:true` and using `hello` for monitoring on supporting servers, which will be implemented separately in CSHARP-3659.
> CSHARP-3516: Use hello command when API Version is declared.

- tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
- tests/MongoDB.Driver.Core.Tests/Specifications/server-discovery-and-monitoring/MonitoringTestRunner.cs
- tests/MongoDB.Driver.Core.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringTestRunner.cs
- tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp365Tests.cs
- tests/MongoDB.Driver.Legacy.Tests/Linq/WithIndexTests.cs
- tests/MongoDB.Driver.Tests/ClusterTests.cs
- tests/MongoDB.Driver.Tests/JsonDrivenTests/JsonDrivenTestFactory.cs
- tests/MongoDB.Driver.Tests/PinnedShardRouterTests.cs
- tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
- tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
- tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/retryable-reads/RetryableReadsTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/retryable-writes/prose-tests/CommandConstructionTests.cs
- tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringIntegrationTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/transactions/TransactionTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/transactions/TransactionUnifiedTestRunner.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
Running patch on latest to verify the fix:
https://spruce.mongodb.com/version/60c27902d1fe0735af1ee280/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CSHARP-3705: Ignore hello commands during event capture for UnifiedTestRunner.

- build.cake
Patch example: https://evergreen.mongodb.com/task_log_raw/dot_net_driver_tests_zstandard_compression__version~4.4_os~windows_64_topology~standalone_auth~noauth_ssl~nossl_compressor~zstandard_test_net452_patch_ad0ad177e25debcef9e6f1875f24d4f2c733662a_60c387852fbabe2d4ec892fb_21_06_11_15_56_07/0?type=T#L901
> CSHARP-3707: Force EG variant running all tests projects even some of them were failed.

- Docs/reference/content/reference/driver/crud/reading.md
This PR does **not** affect the current release.
> CSHARP-3698: Calling cursor.next() and cursor.close() concurrently in Load Balanced mode uses the same connection simultaneously.

- src/MongoDB.Driver.Core/Core/Connections/HelloHelper.cs
- src/MongoDB.Driver.Core/Core/Connections/IsMasterResult.cs
- src/MongoDB.Driver.Core/Core/Servers/LoadBalancedServer.cs
- src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
- src/MongoDB.Driver.Core/Core/Servers/ServerDescription.cs
- src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
- tests/MongoDB.Driver.Core.Tests/Core/Clusters/MultiServerClusterTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/HelloHelperTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/IsMasterResultTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Servers/RoundTripTimeMonitorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerDescriptionTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
- tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
We look at the previous hello/legacy hello response to determine whether hello or legacy hello should be used for the next heartbeat or RTT command. The only slight complexity is that we re-use the previous command/protocol if we are streaming heartbeats from the server.
> CSHARP-3659: Use hello command for monitoring (including RTT) if supported.

- Docs/reference/content/reference/driver/crud/compression.md
- Docs/reference/content/reference/driver_core/index.md
- Docs/reference/content/what_is_new.md
- Docs/reference/themes/mongodb/static/js/navbar.js
The only remaining occurrences of oppressive language in our docs are in the following places:
- the API docs (which will be handled in CSHARP-3660)
- third-party dependencies (jquery.js, underscore.js, etc.)
- explanation that `slaveOk=true` must be replaced with `readPreference` in What's New?
> CSHARP-3661: Remove oppressive language from the documentation.

- build.cake
- evergreen/evergreen.yml
I didn't make any changes for LB since when I make the same change for stopping LB, the whole scripts fails with this error https://evergreen.mongodb.com/task_log_raw/dot_net_driver_load_balancer_tests_secure__version~latest_os~ubuntu_1804_topology~sharded_cluster_auth~auth_ssl~ssl_test_load_balancer_netstandard21_patch_a563175b58fffa0f0ca754c735caa4e32234aaad_6105f384d1fe071f0cb0c6d9_21_08_01_01_06_30/0?type=T#L1614. It looks like stopping logic should be done in the same scope as the main steps. Yes, if something will fail, the stopping logic won't be called. I asked @durran how we can make deal with this, since in the node he applied the same change
> CSHARP-3765: Clean-up a stop step for LB and Serverless tests.

- tests/MongoDB.Driver.Tests/Specifications/sessions/tests/unified/snapshot-sessions-not-supported-client-error.json
- tests/MongoDB.Driver.Tests/Specifications/sessions/tests/unified/snapshot-sessions-not-supported-client-error.yml
> CSHARP-3786: Tests for client-side errors with snapshot reads use incorrect syntax for test.expectEvents.

- build.cake
- tests/AstrolabeWorkloadExecutor/AstrolabeWorkloadExecutor.csproj
- tests/AtlasConnectivity.Tests/AtlasConnectivity.Tests.csproj
- tests/MongoDB.Bson.Tests/Jira/CSharp301Tests.cs
- tests/MongoDB.Bson.Tests/MongoDB.Bson.Tests.csproj
- tests/MongoDB.Bson.Tests/Serialization/Serializers/CollectionSerializerTests.cs
- tests/MongoDB.Bson.Tests/Serialization/Serializers/NetPrimitiveSerializerTests.cs
- tests/MongoDB.Bson.Tests/TargetFrameworkTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/NativeLibraryLoader/NativeLibraryLoaderTests.cs
- tests/MongoDB.Driver.Core.Tests/MongoDB.Driver.Core.Tests.csproj
- tests/MongoDB.Driver.Core.Tests/TargetFrameworkTests.cs
- tests/MongoDB.Driver.Examples/MongoDB.Driver.Examples.csproj
- tests/MongoDB.Driver.GridFS.Tests/MongoDB.Driver.GridFS.Tests.csproj
- tests/MongoDB.Driver.GridFS.Tests/TargetFrameworkTests.cs
- tests/MongoDB.Driver.Legacy.Tests/MongoDB.Driver.Legacy.Tests.csproj
- tests/MongoDB.Driver.Legacy.Tests/TargetFrameworkTests.cs
- tests/MongoDB.Driver.TestConsoleApplication/MongoDB.Driver.TestConsoleApplication.csproj
- tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
- tests/MongoDB.Driver.Tests/TargetFrameworkTests.cs
Running the full suite overnight to verify that updating from `netcoreapp3.0` to `netcoreapp3.1` to run tests doesn't break anything. It shouldn't because the build servers didn't have `netcoreapp3.0` installed and have been running tests on `netcoreapp3.1` for awhile now.
> CSHARP-3875: Update netstandard2.1 to run on netcoreapp3.1 to remove netcoreapp3.0 out of support warnings

- evergreen/evergreen.yml
- evergreen/prepare-ocsp.sh
When the `evergreen/prepare-ocsp.sh` script was extracted from `evergreen/evergreen.yml`, the working directory was not set to `mongo-csharp-driver`. Thus Evergreen was trying to run the script from the wrong directory and couldn't find it.
> CSHARP-3434: Fixed OCSP tests in Evergreen.

- build.cake
- build.config
- src/MongoDB.Bson/MongoDB.Bson.csproj
- src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
- src/MongoDB.Driver.GridFS/MongoDB.Driver.GridFS.csproj
- src/MongoDB.Driver.Legacy/MongoDB.Driver.Legacy.csproj
- src/MongoDB.Driver/MongoDB.Driver.csproj
- tools/packages.config
Some notes:
1. Currently I temporally switched back to myget for tests reasons, probably we will know that it works with nuget only during next release.
2. In the scope of this ticket I also fixed nuget package warnings from [here](https://jira.mongodb.org/browse/CSHARP-3802) and [here](https://jira.mongodb.org/browse/CSHARP-3047). Steps that I took more or less taken from [here](https://lurumad.github.io/using-source-link-in-net-projects-and-how-to-configure-visual-studio-to-use-it).
After this PR, the nuget package manager should look like this:
NOTE: it looks like myget doesn't work correctly with the above package validation, all nuget packages that I checked (including external) were red. Probably it's only myget issue. Will check it after release :) 
3. I needed to update cake to …
> CSHARP-2088: Publish PDBs and sources on symbolsource.

- evergreen/cleanup-test-resources.sh
- evergreen/compile.sh
- evergreen/get-python-path.sh
- evergreen/publish.sh
- evergreen/run-atlas-connectivity-tests.sh
- evergreen/run-atlas-data-lake-test.sh
- evergreen/run-gssapi-auth-tests.sh
- evergreen/run-load-balancer-tests.sh
- evergreen/run-plain-auth-tests.sh
- evergreen/set-temp-fle-aws-creds.sh
- evergreen/set-virtualenv.sh
EG: https://evergreen.mongodb.com/version/61b7e7463627e00295e8b335
> CSHARP-3996: Fix cleanup-test-resources on Linux and Macos.

- src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
Straightforward upgrade to DnsClient.NET. I was able to connect to MongoDB Atlas using `mongodb+srv://` in a test project. Open to suggestions of anything else I should verify before merging.
> CSHARP-4001: Upgrade to DnsClient.NET 1.6.0, which includes the fix for duplicate DNS responses.

- src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
- src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
- src/MongoDB.Driver.Core/Core/Clusters/LoadBalancedCluster.cs
- src/MongoDB.Driver/ClientSessionHandle.cs
- tests/MongoDB.Driver.Core.Tests/Core/Bindings/CoreSessionTests.cs
- tests/MongoDB.Driver.Tests/ClientSessionHandleTests.cs
- tests/MongoDB.Driver.Tests/MockOperationExecutor.cs
- tests/MongoDB.Driver.Tests/MongoClientTests.cs
- tests/MongoDB.Driver.Tests/MongoCollectionImplTests.cs
- tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
- tests/MongoDB.Driver.Tests/Specifications/sessions/SessionsProseTests.cs
[EG](https://evergreen.mongodb.com/version/620544200305b97e469d3658)
> CSHARP-3927: Drivers should check out an implicit session only after checking out a connection

- src/MongoDB.Driver/Linq/Linq3Implementation/MongoQuery.cs
Attempting to repro CSHARP-3614 (among others), the following output is displayed:
```
Cannot find serializer for null.
```
With this change, the full (and much more informative) stack trace is included:
```
System.InvalidOperationException: Cannot find serializer for null.
at MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializersRegistry.GetSerializer(Expression expression, IBsonSerializer defaultSerializer) in /Users/james/Dropbox/code/mongodb/mongo-csharp-driver/src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/KnownSerializers/KnownSerializersRegistry.cs:line 43
at MongoDB.Driver.Linq.Linq3Implementation.Translators.ExpressionToAggregationExpressionTranslators.ConstantExpressionToAggregationExpressionTranslator.Translate(TranslationContext context, …
```
> CSHARP-4082: Include full stack trace when LINQ3 MongoQuery.ToString() encounters an unexpected exception.

- src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/StringMethod.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ContainsMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/StartsWithContainsOrEndsWithMethodToAggregationExpressionTranslator.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4090Tests.cs
CSHARP-4090: Implement support for string.Contains(match, StringComparison).
CSHARP-4092: Fix case-insensitive StartsWith/EndsWith to generate correct MQL.
> CSHARP-4090 / CSHARP-4092

- src/MongoDB.Driver.Core/ChangeStreamDocument.cs
- src/MongoDB.Driver.Core/ChangeStreamDocumentDatabaseNamespaceSerializer.cs
- src/MongoDB.Driver.Core/ChangeStreamDocumentSerializer.cs
- src/MongoDB.Driver.Core/ChangeStreamOperationType.cs
- src/MongoDB.Driver.Core/ChangeStreamOperationTypeSerializer.cs
- tests/MongoDB.Driver.Core.Tests/ChangeStreamDocumentSerializerTests.cs
- tests/MongoDB.Driver.Core.Tests/ChangeStreamDocumentTests.cs
- tests/MongoDB.Driver.Core.Tests/ChangeStreamOperationTypeSerializerTests.cs
- tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams.json
- tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams.yml
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedRenameCollectionOperation.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
CSHARP-4117: Change Stream event document missing "to" field for rename events
[EG](https://evergreen.mongodb.com/version/625471743e8e86172730bd47)
> CSHARP-4036: Do not error when parsing change stream event documents

- src/MongoDB.Driver.Core/Core/Misc/Feature.cs
- src/MongoDB.Driver.Core/Core/Operations/AsyncCursor.cs
- tests/MongoDB.Driver.Core.Tests/Core/Operations/AsyncCursorTests.cs
- tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams.json
- tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams.yml
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/aggregate.json
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/aggregate.yml
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/find-comment.json
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/find-comment.yml
Also
CSHARP-4109: Test getMore with comment on all topologies
> CSHARP-4108: Inherited comment causes OperationFailure on MongoDB <4.4.0

- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/badQueries.json
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/badQueries.yml
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/types.json
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/types.yml
[EG](https://evergreen.mongodb.com/version/625713e10305b93ec0ffe5b2)
> CSHARP-4136: CSFLE badQueries and types errorContains failing to match on mongocryptd 6.0.0-alpha

- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/noSchema.json
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/tests/noSchema.yml
As far as I understood, the auto CSFLE behavior with no schema can be different and sometimes libmongocrypt can throw exception. Kevin mentioned this case: `an aggregate with $lookup stage to another collection`. But for this particular test case, no schema means no encryption, even though some inner machinery still will be involved
> CSHARP-4135: Add CSFLE spec test for auto encryption on a collection with no jsonSchema.

- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/aggregate-allowdiskuse.json
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/aggregate-allowdiskuse.yml
Sync'd new `aggregate-allowdiskuse.[json|yml]`. No production code changes necessary as we use `bool? AllowDiskUse` throughout the driver. If `AllowDiskUse` isn't set explicitly, we use the server's default, which is false on pre-6.0 and true on 6.0 or later.
> CSHARP-4138: Added new allowDiskUse tests.

- evergreen/evergreen.yml
Similar to CSHARP-4155 except adding the quarterly rapid releases to our test matrix.
> CSHARP-4156: Test against MongoDB quarterly rapid releases

- src/MongoDB.Driver.Core/ChangeStreamDocument.cs
- src/MongoDB.Driver.Core/ChangeStreamDocumentSerializer.cs
- src/MongoDB.Driver.Core/ChangeStreamFullDocumentBeforeChangeOption.cs
- src/MongoDB.Driver.Core/Core/Misc/Feature.cs
- src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
- src/MongoDB.Driver.Core/Core/Operations/ChangeStreamOperation.cs
- src/MongoDB.Driver/ChangeStreamHelper.cs
- src/MongoDB.Driver/ChangeStreamOptions.cs
- src/MongoDB.Driver/CreateCollectionOptions.cs
- tests/MongoDB.Driver.Core.Tests/ChangeStreamDocumentSerializerTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Misc/WireVersionTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Operations/ChangeStreamOperationTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Operations/CreateCollectionOperationTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Operations/OperationTestBase.cs
- tests/MongoDB.Driver.Tests/ChangeStreamHelperTests.cs
- tests/MongoDB.Driver.Tests/MongoCollectionImplTests.cs
- tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
- tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams-pre_and_post_images.json
- tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams-pre_and_post_images.yml
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateChangeStreamOnCollectionOperation.cs
[EG](https://spruce.mongodb.com/version/625db17e7742ae58d2d83865)
> CSHARP-4034: Change streams support for user-facing PIT pre- and post-images

- Docs/reference/content/reference/driver/admin.md
- src/MongoDB.Driver.Core/Core/Misc/Feature.cs
- src/MongoDB.Driver.Core/Core/Operations/CreateCollectionOperation.cs
- src/MongoDB.Driver/ClusteredIndexOptions.cs
- src/MongoDB.Driver/CreateCollectionOptions.cs
- src/MongoDB.Driver/CreateIndexModel.cs
- src/MongoDB.Driver/MongoDatabaseImpl.cs
- tests/MongoDB.Driver.Core.Tests/Core/Operations/CreateCollectionOperationTests.cs
- tests/MongoDB.Driver.TestConsoleApplication/Program.cs
- tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
- tests/MongoDB.Driver.Tests/Specifications/collection-management/tests/clustered-indexes.json
- tests/MongoDB.Driver.Tests/Specifications/collection-management/tests/clustered-indexes.yml
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateCollectionOperation.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListCollectionsOperation.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListIndexesOperation.cs
The API to create a clustered index is:
```
var options = new CreateCollectionOptions<Product>
{
ClusteredIndex = new ClusteredIndexOptions<Product>
{
Key = Builders<Product>.IndexKeys.Ascending(x => x.Id),
Unique = true,
Name = "custom clustered index key name"
}
};
db.CreateCollection("products", options);
```
The `Key` must be `{ _id: 1 }` and `Unique` must be `true` at the moment, but the spec was written in such a way that the server can remove these requirements in the future and not require additional work by drivers. If you create a `new ClusteredIndexOptions<T>()`, these options will be defaulted automatically.
Ideally I wanted to support non-generic `CreateCollectionsOptions.ClusteredIndex`, but `CreateCollectionOptions<TDocument>` derives from `CreateCollectionOptions`. I …
> CSHARP-4141: Clustered Indexes for all Collections.

- evergreen/evergreen.yml
EG: https://evergreen.mongodb.com/version/6286ac582fbabe0be724d3b0
> CSHARP-4171: Support for Deploying MongoDB behind a L4 Load Balancer 5.0 Backports.

- src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
MongoDB.Driver connections fail in .net core 3.1 Azure Functions (v3)
> CSHARP-4200: DnsClient version update

- tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
- tests/MongoDB.Driver.Examples/MongoDB.Driver.Examples.csproj
How to configure AWS auth for atlas cluster:
1. Get your AWS_* (aws_access_key_id, aws_secret_access_key, aws_session_token) credentials in Single Sign-on page:
Pay attention that values should be regenerated from time to time.
2. Configure credentials folder here: `c:\Users\{user_name}\.aws\`
3. Get your arn via `get-caller-identity`:
$ ./aws sts get-caller-identity
{
"UserId": "blablabla:[dmitry.lukyanov@mongodb.com](mailto:dmitry.lukyanov@mongodb.com)",
"Account": "%ID_VALUE%",
"Arn": "arn:aws:sts::%ID_VALUE%:assumed-role/%ROLE_NAME%/[dmitry.lukyanov@mongodb.com](mailto:dmitry.lukyanov@mongodb.com)"
}
pay attention on %ROLE_NAME%
4. list all roles via:
$ ./aws iam list-roles
{
"Roles": [
{
"Path": "..",
"RoleName": "%ROLE_NAME%",
"Arn": "arn:aws...:
...
in the provided roles, search …
> CSHARP-4127: Language specific examples for AWS Lambda.

- src/MongoDB.Driver.Core/MongoDB.Driver.Core.targets
We found a problem in target build for msbuild that seems
to break web project publishing in MsBuild. The modification
done at the target includes multiple times the same file
making publishing from MsBuild commandline to fail.
Details are in jira https://jira.mongodb.org/browse/CSHARP-4214
I'm not entirely sure of the fix, previous version of the file was really simpler, it includes explicitly the dll that should be included, this version uses overlapping wildcard that generates issue.
> CSHARP-4214: Fixed Build target.

- src/MongoDB.Driver.Core/Core/Connections/ConnectionInitializer.cs
- src/MongoDB.Driver.Core/Core/Connections/HelloResult.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/HelloResultTests.cs
The mongocryptd's `hello` response:
MongoDB Enterprise > db.isMaster()
{
"ismaster" : true,
"iscryptd" : true,
"maxBsonObjectSize" : 16777216,
"maxMessageSizeBytes" : 48000000,
"localTime" : ISODate("2022-06-22T01:27:36.854Z"),
"maxWireVersion" : 17,
"minWireVersion" : 0,
"ok" : 1
}
> CSHARP-3191: driver tries to run getLastError on mongocryptd that does not exists.

- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/distinct-comment.json
- tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/distinct-comment.yml
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedDistinctOperation.cs
Comment for distinct was implemented previously. This commit simply adds unified tests for the functionality.
> CSHARP-4184: Sync'd distinct-commnet tests from CRUD spec and updated unified runner.

- Docs/reference/content/common_issues.md
- Docs/reference/content/frequently_encountered_issues.md
- Docs/reference/content/issues_help.md
I'm not sure what we can suggest for these tickets:
* https://jira.mongodb.org/browse/CSHARP-2489
* https://jira.mongodb.org/browse/CSHARP-1677
it looks like too easy and straightforward questions, thoughts?
NOTE: to deploy changes locally, use this hugo command:
..\mongo-csharp-driver\Docs\reference>hugo.exe server
> CSHARP-4021: Add section to troubleshooting FAQ per driver with top SEO results.

- Docs/reference/themes/mongodb/static/css/overrides.css
This PR adds a printer-specific section (`@media print`) to the CSS for the reference documentation to fix a number of things that were causing the pages to not look right when printed.  The appearance when viewing on screen is unaffected.  I've tested by running locally with
```
hugo server --baseUrl=http://localhost --buildDrafts --watch
```
There is an issue where the CSS used in the browser reverts back to the original version when the page is refreshed or the user navigates to a different page.  I'm not sure exactly why.  Before merging, we would need to ensure that the issue does not occur when viewing the documentation for real or fix whatever is causing it.
Before:
After:
> Skunkworks: Tweak CSS for printing

- src/MongoDB.Driver.Core/Core/Connections/TcpStreamFactory.cs
- src/MongoDB.Driver.Core/Core/Misc/OperatingSystemHelper.cs
Only call Socket.IOControl with IOControlCode.KeepAliveValues on Windows as non-Windows platforms will always throw PlatformNotSupportedExceptions.
> CSHARP-4287: Only call Socket.IOControl on Windows

- README.md
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MemberExpressionToAggregationExpressionTranslator.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4316Tests.cs
We were accidentally matching all properties named `Value` or `HasValue` even if they weren't on `Nullable<T>` types.
> CSHARP-4316: Ensure that LINQ3 only applies Nullable property translators to Nullables types and not properties with similar names.

- src/MongoDB.Driver.Core/ChangeStreamDocument.cs
- src/MongoDB.Driver.Core/ChangeStreamDocumentSerializer.cs
- tests/MongoDB.Driver.Core.Tests/ChangeStreamDocumentSerializerTests.cs
- tests/MongoDB.Driver.Core.Tests/ChangeStreamDocumentTests.cs
- tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams-disambiguatedPaths.json
- tests/MongoDB.Driver.Tests/Specifications/change-streams/tests/unified/change-streams-disambiguatedPaths.yml
Changes should be self-explanatory. The remarks are copied from the spec update that added the new field.
> CSHARP-4274: Added DisambiguatedPaths to ChangeStreamDocument.

- evergreen/evergreen.yml
- src/MongoDB.Driver.Core/Core/Authentication/External/AwsAuthenticationCredentialsProvider.cs
- src/MongoDB.Driver.Core/Core/Authentication/External/CacheableCredentialsProvider.cs
- src/MongoDB.Driver.Core/Core/Authentication/External/ExternalCredentialsAuthenticators.cs
- src/MongoDB.Driver.Core/Core/Authentication/External/GcpAuthenticationCredentialsProvider.cs
- src/MongoDB.Driver.Core/Core/Authentication/External/IExternalCredentials.cs
- src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
- src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/CacheableCredentialsProviderTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoAWSAuthenticatorTests.cs
- tests/MongoDB.Driver.Tests/Communication/Security/AwsAuthenticationTests.cs
Some notes:
1. The spec requirement about dedicated thread is removed at this point. so we just save creds somewhere globally. Spec should be updated. cc: @blink1073 
2. There is an open question about clearing cache for CSFLE. (update: https://jira.mongodb.org/browse/DRIVERS-2464. It's about Azure, but I guess for Aws we can mimic their solution)
> CSHARP-4273: Cache AWS Credentials Where Possible.

- tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3197Tests.cs
Don't know what transformations LINQ2 tried to do when there were two Selects in a row, but in LINQ3 if you write two Selects you get two $projects.
> CSHARP-3197: Verify that Select/Select works in LINQ3.

- src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
- src/MongoDB.Driver.Core/Core/Clusters/LoadBalancedCluster.cs
- src/MongoDB.Driver.Core/Core/Logging/LogCategories.cs
- src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
- tests/MongoDB.Driver.Core.Tests/Core/Logging/EventLoggerTests.cs
- tests/MongoDB.Driver.Tests/LoggingTests.cs
- tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LoggingTests.cs
- Fix "Invalidating description" log message in DefaultServer
SDAM category was mistakenly split to Cluster and SDAM categories. Spec specifies single category for both.
> CSHARP-4406: Unite logging "Cluster" and "Sdam" categories

- evergreen/evergreen.yml
- evergreen/run-mongodb-aws-ecs-test.sh
- src/MongoDB.Driver.Core/Core/Authentication/External/AwsAuthenticationCredentialsProvider.cs
- src/MongoDB.Driver.Core/Core/Authentication/External/CacheableCredentialsProvider.cs
- src/MongoDB.Driver.Core/Core/Authentication/External/ExternalCredentialsAuthenticators.cs
- src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
- src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
- tests/MongoDB.Driver.Tests/Communication/Security/AwsAuthenticationTests.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
Asked a question about possible thead safe issue: https://github.com/aws/aws-sdk-net/discussions/2487
> CSHARP-3740: Add native support for AWS IAM Roles for service accounts, EKS in particular.

- Docs/reference/content/reference/driver/index.md
- Docs/reference/content/reference/driver/logging.md
Preview [here](https://borisdog.github.io/mongo-csharp-driver/2.18/reference/driver/logging/).
> CSHARP-4387: Logging documentation

- Docs/reference/content/reference/driver_core/index.md
Including correct commands and information on polling (<=4.2) versus streaming (>=4.4).
> CSHARP-4327: Update Server Monitoring documentation

- src/MongoDB.Driver.Core/Core/Connections/ConnectionId.cs
- src/MongoDB.Driver.Core/Core/Events/Diagnostics/TraceSourceEventHelper.cs
- src/MongoDB.Driver.Core/Core/Logging/StructuredLogTemplateProviders.cs
- src/MongoDB.Driver.Core/Core/Logging/StructuredLogTemplateProvidersCommand.cs
- src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
- src/MongoDB.Driver.Core/MongoCursorNotFoundException.cs
- tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
- tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/MaintenanceHelperTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionIdTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionInitializerTests.cs
- tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
ConnectionId should use longs for LocalValue and ServerValue to match 64-bit integer connectionId returned from the server.
> CSHARP-4417: ConnectionId should use longs for LocalValue and ServerValue

- src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
- tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
Without applied fix, a consumer will see:
and therefore will be able to use aws sdk public classes.
The applied change hides this internal (for the driver) classes from consumers. 
As a result, aws.sdk public classes will be unavailable for driver's consumers
> CSHARP-4442: Hide aws sdk in release package.

- evergreen/evergreen.yml
Related spec https://github.com/mongodb/specifications/pull/1351 and EG tools https://github.com/mongodb-labs/drivers-evergreen-tools/pull/247 PRs
> CSHARP-4355: Test crypt_shared with older server versions.

- src/MongoDB.Bson/ObjectModel/BsonTypeMapper.cs
The error message to display when a BsonDocument is being mapped to an invalid type showed the target type name for BsonArray.
> CSHARP-4465: Include correct type in exception in BsonTypeMapper.MapToDotNetValue.

- src/MongoDB.Bson/IO/JsonReader.cs
- src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
- tests/MongoDB.Bson.Tests/Jira/CSharp4496.cs
- tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
Added support for `ObjectSerializer` to both read and write `Decimal128` data type.
> CSHARP-4496: Add decimal support to ObjectSerializer.

- src/MongoDB.Driver.Core/Core/Connections/ConnectionInitializer.cs
- src/MongoDB.Driver.Core/Core/Connections/HelloResult.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionInitializerTests.cs
Although CSHARP-4417 changes the client and server connectionIds to use `int64`, the server description update code path was not tested. The update code path is where the server response is used update the `ConnectionId.LongServerValue`. `HelloResult.ConnectionIdServerValue` still parsed `connectionId` in the response as an `int32`. This has been fixed and additional tests added.
Although `HelloResult` is public, it is in Core. We renamed this class during the offensive language removal initiative and no one complained. Thus changing the data type of `HelloResult.ConnectionIdServerValue` from `int?` to `long?` shouldn't be problematic.
> CSHARP-4483: connectionId returned in heartbeats may be int32, double, or int64.

- src/MongoDB.Driver.Core/Core/Misc/Feature.cs
- src/MongoDB.Driver.GridFS/GridFSBucket.cs
- tests/MongoDB.Driver.GridFS.Tests/GridFSBucketTests.cs
`GridFSBucket.Find` was failing because we always included `noCursorTimeout` even when not specified. `noCursorTimeout` is not supported with Stable API. That change was simple (removing the defaulting to false), but we had no integration tests around GridFS. Additionally while we test Stable API, we don't test it in strict mode nor do we have a mechanism to do so. I added `Feature.StableApi` so that I could write a strict mode Stable API test. Feedback appreciated especially if you can think of a better way to test it.
> CSHARP-4595: Support GridFS with Stable API.

- tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
[Failure](https://evergreen.mongodb.com/task/dot_net_driver_load_balancer_tests__version~rapid_os~ubuntu_1804_topology~sharded_cluster_auth~noauth_ssl~nossl_test_load_balancer_netstandard21_32f1d3069af21a68de56f88fe43dc6c36f12dd28_23_06_15_15_18_44)
> CSHARP-4677: Server selection logging tests fail on Load Balancer

- evergreen/evergreen.yml
Using `python` worked until some OS variants started to map `python` to `python2` but others `python3`. The standard way to work around this is to use `python3` where you require `python3`, but some variants (cough cough Windows) don't map `python3`.
I tried the alternate approach of doing `python3` detection as many of our OCSP and other tests do. Unfortunately these aliases are evaluated before `drivers-evergreen-tools` is sourced and thus our `python3` detection scripts aren't available yet.
I then tried switching to `jq -sRjr @uri` for `urlencode`, which worked great except some MacOS machines don't have `jq` installed and the EG user doesn't have sufficient privileges to run `brew install jq`.
This lead me to take the same approach as `mongo-python-driver` to ensure that `python3` is …
> CSHARP-4626: Fix urlencode on MacOS variants.

- src/MongoDB.Driver/AggregateFluent.cs
- src/MongoDB.Driver/AggregateFluentBase.cs
- src/MongoDB.Driver/IAggregateFluent.cs
- src/MongoDB.Driver/Linq/MongoQueryable.cs
- src/MongoDB.Driver/PipelineDefinitionBuilder.cs
- src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
- tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
- tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
The 10 July 2023 release of MongoDB Atlas Search introduced the sort option.
[Atlas Search Changelog - 10 July 2023 Release](https://www.mongodb.com/docs/atlas/atlas-search/changelog/#10-july-2023-release)
[Sort Atlas Search Results](https://www.mongodb.com/docs/atlas/atlas-search/sort/#std-label-sort-ref)
It would be very nice to have access to the sort field from the C# driver
> CSHARP-4728: Add implementation for Atlas Search Sort

- src/MongoDB.Bson/IO/BinaryPrimitivesCompat.cs
- src/MongoDB.Bson/IO/BsonStreamAdapter.cs
- src/MongoDB.Bson/IO/ByteBufferStream.cs
- src/MongoDB.Bson/IO/ElementAppendingBsonWriter.cs
- src/MongoDB.Bson/MongoDB.Bson.csproj
- src/MongoDB.Bson/ObjectModel/GuidConverter.cs
- src/MongoDB.Bson/Serialization/IdGenerators/AscendingGuidGenerator.cs
- src/MongoDB.Bson/Serialization/IdGenerators/CombGuidGenerator.cs
- src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
- src/MongoDB.Driver.Core/Core/Connections/KeepAliveValues.cs
- tests/MongoDB.Bson.Tests/IO/BsonStreamAdapterTests.cs
- tests/MongoDB.Bson.Tests/IO/BsonStreamExtensionsTests.cs
- tests/MongoDB.Bson.Tests/IO/ByteBufferStreamTests.cs
- tests/MongoDB.Bson.Tests/Serialization/IdGenerators/AscendingGuidGeneratorTests.cs
- tests/MongoDB.Bson.Tests/Serialization/IdGenerators/CombGuidGeneratorTests.cs
Creating a new PR rebased on master to trigger a patch build.
Original PR is:
https://github.com/mongodb/mongo-csharp-driver/pull/1108
> CSHARP-4676: Add MongoDB.Driver support for big-endian clients.

- src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
- src/MongoDB.Driver/Search/SearchOptions.cs
- src/MongoDB.Driver/Search/SearchTrackingOptions.cs
- tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
The 7 June 2023 release of MongoDB Atlas Search introduced support for tracking search terms.
[07 June 2023 Release](https://www.mongodb.com/docs/atlas/atlas-search/changelog/#07-june-2023-release)
[Track search terms](https://www.mongodb.com/docs/atlas/atlas-search/tracking/#std-label-fts-tracking-ref)
It would be very nice to have access to the tracking field from the C# driver
> CSHARP-4733: Add implementation for Atlas Search Tracking search terms

- uuidhelpers.js
Based on [question in the community forums](https://www.mongodb.com/community/forums/t/c-decode-and-encode-guids-in-mongosh/244163). It was easy enough to shim the existing script so that it works in both old and new shells.
> CSHARP-4786: Added shim to uuidhelpers.js so that it works in both the old mongo shell as well as the new mongosh shell.

- specifications/connection-string/tests/README.rst
- specifications/connection-string/tests/invalid-uris.json
- specifications/connection-string/tests/invalid-uris.yml
- specifications/connection-string/tests/valid-auth.json
- specifications/connection-string/tests/valid-auth.yml
- specifications/connection-string/tests/valid-host_identifiers.json
- specifications/connection-string/tests/valid-options.json
- specifications/connection-string/tests/valid-options.yml
- specifications/connection-string/tests/valid-unix_socket-absolute.json
- specifications/connection-string/tests/valid-unix_socket-relative.json
- specifications/connection-string/tests/valid-warnings.json
- specifications/connection-string/tests/valid-warnings.yml
- tests/MongoDB.Driver.Tests/Specifications/connection-string/ConnectionStringTestRunner.cs
I sync'd `$/specifications/connection-string/tests` to the spec repo. The changes are minimal and all tests pass. The reason for the large diff is a formatting change in the JSON files. The YAML files (from which the JSON files were generated) were not significantly altered.
> CSHARP-4792: Verify that delimiting slash bewteen hosts and options is optional.

- evergreen/evergreen.yml
This is an additional cleanup step if the EC2 instance profile was changed during variant setup for MONGODB-AWS auth testing. This should improve the stability of the EG environment and avoid failures on future runs by any driver when run on the same host.
> CSHARP-4714: Reset EC2 instance profile at end of test if necessary.

- .editorconfig
- .gitignore
- evergreen/evergreen.yml
- evergreen/install-dotnet.sh
- evergreen/packages-pack.sh
- evergreen/packages-push.sh
- evergreen/packages-version.sh
- src/MongoDB.Bson/MongoDB.Bson.csproj
- src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
- src/MongoDB.Driver.GridFS/MongoDB.Driver.GridFS.csproj
- src/MongoDB.Driver.Legacy/MongoDB.Driver.Legacy.csproj
- src/MongoDB.Driver/MongoDB.Driver.csproj
Link to CI:
https://spruce.mongodb.com/commits/dot-net-driver-ci-experiments
Example of the build run by tag:
https://spruce.mongodb.com/version/dot_net_driver_ci_experiments_v0.0.1_dev44_64ee6d6a32f417766ac6bd2f
> CSHARP-4765: CI script to generate Driver's dev-package

- evergreen/evergreen.yml
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
Also I've reorganized build variants a little, but I've double-checked and current pipeline have the same amount of tasks run + 1 (for auth test task for new defined OS). Here is a link to the test evergreen pipeline:
https://spruce.mongodb.com/version/dot_net_driver_ci_experiments_5765b0e7f76b2cd7747d0d0906e909ac40599b88/tasks
Please also note: not all problems are solved yet. We still have a problems with running AWS tests.
> CSHARP-4805: Use Ubuntu 20.04 for MongoDB 7.0+ on Evergreen

- evergreen/evergreen.yml
Basically the main change is in EG project settings as BUILD team provided  new arn.
> CSHARP-4814: Update AWS Auth test host and ECS Task

- specifications/collection-management/tests/timeseries-collection.json
- specifications/collection-management/tests/timeseries-collection.yml
- src/MongoDB.Driver.Core/TimeSeriesOptions.cs
- tests/MongoDB.Driver.Core.Tests/TimeSeriesOptionsTests.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateCollectionOperation.cs
Adds support for additional time series options when creating a collection.
- Updates collection management spec tests.
- Adds 2 new options to TimeSeriesOptions, bucketMaxSpanSeconds and bucketRoundingSeconds.
> CSHARP-4539: Improving Time Series Bucketing Scalability

- src/MongoDB.Driver.Core/Core/Configuration/SslStreamSettings.cs
- src/MongoDB.Driver/SslSettings.cs
- tests/MongoDB.Driver.Core.Tests/Core/Configuration/SslStreamSettingsTests.cs
- tests/MongoDB.Driver.Tests/SslSettingsTests.cs
We don't explicitly test different TLS versions as we rely on the underlying TLS libraries to negotiate the protocol. This commit opts into TLS1.3 as an option. I verified that a `netcoreapp2.1` could still connect to an Atlas cluster with TLS1.2 enabled after adding the enum value for TLS1.3 to the flags. The value of the `SslProtocols.Tls13` flag is from:
https://learn.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=net-8.0
> CSHARP-4862: Include TLS1.3 in the list of acceptable TLS protocols.

- src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityContext.cs
- src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/NativeMethods.cs
- tests/MongoDB.Driver.Core.Tests/Core/Authentication/Libgssapi/GssapiSecurityCredentialTests.cs
When calling `gss_delete_sec_context` we passed in a handle (aka `IntPtr` aka `void*`), but the function was expecting a `void**`. Strangely the function returned success even when passed a `void*` rather than a `void**`.
> CSHARP-4797: Fix segfault when disposing of GSSAPI (Kerberos) security context on Linux.

- src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
- tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Misc/WireVersionTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerDescriptionTests.cs
- Add wireVersions 22 and 23 to list of known wireVersions and updates tests as needed.
- Check that I updated everything that needs to be updated.
> CSHARP-4965: Bump maxWireVersion for MongoDB 7.2

- specifications/retryable-writes/tests/unified/insertOne-serverErrors.json
- specifications/retryable-writes/tests/unified/insertOne-serverErrors.yml
The gist of  DRIVERS-1641 is:
Drivers MUST NOT add a RetryableWriteError label based on the following:
- any `writeErrors[].code` fields in a mongod or mongos response
- the `writeConcernError.code` field in a mongos response
when connected to a pre-4.4 server.
I added the new unified tests and they pass without any changes to the driver.
I searched the driver code base for uses of `.Code` and verified that we are not adding a `RetryableWriteError` anywhere based on the value of `Code`.
> CSHARP-4827: Verify that driver does not add RetryableWriteError when it should not.

- evergreen/evergreen.yml
Run packages-pack on Windows host + set priority to 10 for all package-related tasks.
> CSHARP-4962: Fix package build script on CI to produce 472 binaries

- evergreen/build-packages.sh
- src/Directory.Build.props
Added EmbedUntrackedSources attribute and set ContinuousIntegrationBuild to true to make nuget validation happy. Screenshot from the locally built package after the changes:
> CSHARP-3994: Consider adding EmbedUntrackedSources for a build process

- tests/MongoDB.Bson.TestHelpers/Threading/TasksUtils.cs
- tests/MongoDB.Bson.TestHelpers/Threading/ThreadingUtilities.cs
Test console before the fix:
1 - sync method works as expected.
2 - async method "exit" before inner operations are completed.
Test console after the fix:
both sync and async methods work as expected:
> Make ThreadingUtilities.ExecuteTasksOnNewThreads await on the operations completion.

- specifications/initial-dns-seedlist-discovery/tests/replica-set/srv-service-name.json
- specifications/initial-dns-seedlist-discovery/tests/replica-set/srv-service-name.yml
- src/MongoDB.Driver.Core/Core/Clusters/DnsMonitor.cs
- src/MongoDB.Driver.Core/Core/Clusters/DnsMonitorFactory.cs
- src/MongoDB.Driver.Core/Core/Clusters/IDnsMonitorFactory.cs
- src/MongoDB.Driver.Core/Core/Clusters/LoadBalancedCluster.cs
- src/MongoDB.Driver.Core/Core/Clusters/MultiServerCluster.cs
- src/MongoDB.Driver.Core/Core/Configuration/ClusterSettings.cs
- src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
- src/MongoDB.Driver.Core/MongoInternalDefaults.cs
- src/MongoDB.Driver.Legacy/MongoServerSettings.cs
- src/MongoDB.Driver/ClusterKey.cs
- src/MongoDB.Driver/MongoClientSettings.cs
- src/MongoDB.Driver/MongoDefaults.cs
- src/MongoDB.Driver/MongoUrl.cs
- src/MongoDB.Driver/MongoUrlBuilder.cs
- tests/MongoDB.Driver.Core.Tests/Core/Clusters/DnsMonitorFactoryTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Clusters/DnsMonitorTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Clusters/LoadBalancedClusterTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Clusters/MultiServerClusterTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Configuration/ClusterSettingsTests.cs
- tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
- tests/MongoDB.Driver.Tests/ClusterKeyTests.cs
- tests/MongoDB.Driver.Tests/ClusterRegistryTests.cs
- tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
- tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
- tests/MongoDB.Driver.Tests/MongoUrlTests.cs
- tests/MongoDB.Driver.Tests/Specifications/connection-string/ConnectionStringTestRunner.cs
- Added a new URI options `srvServiceName` which allows the user to change the srv address prefix from the default of `mongodb`
> CSHARP-3745: Add support for srvServiceName URI option

- src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs
- tests/MongoDB.Bson.Tests/Serialization/BsonClassMapSerializerTests.cs
When you have a class in a hierarchy of classes that has no suitable constructor to be desrialized (look also at [CSHARP-3186](https://jira.mongodb.org/browse/CSHARP-3186)), I got a simple error 
```
An error occurred while deserializing the Nodes property of class xxx.xxxx.ReportDocumentConfigurationValueObject: No matching creator found
```
The problem is that nodes property of that class can have like 10 concrete classes, and the error is on one specific class. With this patch the error contains the exact class that miss the constructor. This will surely speed up the diagnose of errors.
> CSHARP-5007: Better error when no matching constructor found

- evergreen/build-apidocs.sh
- evergreen/build-packages.sh
- evergreen/evergreen.yml
Change sh to bash as per Driver ticket request.
> CSHARP-5004: Invoke all Drivers Evergreen Tools Scripts with Bash

- specifications/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-maxConnecting-is-enforced.json
- specifications/connection-monitoring-and-pooling/tests/cmap-format/pool-checkout-maxConnecting-is-enforced.yml
- tests/MongoDB.Driver.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs
These timings seem to solve the issue.
> CSHARP-3995: Fix flaky pool-checkout-maxConnecting-is-enforced.json:maxConnecting_is_enforced

- src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
- src/MongoDB.Driver.Core/Core/Misc/FileSystemProvider.cs
- src/MongoDB.Driver.Core/Core/Misc/FileWrapper.cs
- tests/MongoDB.Driver.Core.Tests/Core/Connections/ClientDocumentHelperTests.cs
Enables container and kubernetes awareness in the driver as specified in the [MongoDB Handshake Spec](https://github.com/abr-egn/specifications/blob/c4831b426c7eab8749723d7f3cd6bb5c237bcbbe/source/mongodb-handshake/handshake.rst#container) .
- Allows Product to track user usage of docker and kubernetes.
> CSHARP-4718: Enable Container and kubernetes awareness

- benchmarks/MongoDB.Driver.Benchmarks/MongoDB.Driver.Benchmarks.csproj
- evergreen/evergreen.yml
Change performance test to be run on net8.0 to follow the framework installed by install-dotnet function.
I've configured PR patch to include the perf tests variant to show it working now.
> Update performance tests to run on net8.0

- src/MongoDB.Driver/IClientSession.cs
- tests/MongoDB.Driver.Examples/TransactionExamplesForDocs/WithTransactionExample1.cs
The withTransaction function docs now has more information on error handling to avoid an application entering an infinite loop in the event that a failed command aborts the transaction and causes the transaction to be retried. I've added "Docs Changes Needed" to the ticket description, asking the docs team to call this out when the transaction page is created.
> CSHARP-4828: Handling errors in WithTransaction

- purls.txt
- sbom.json
Adds the generated SBOM file as part of the Silk prep work.
purls.txt - this file houses the [package URLs](https://github.com/package-url/purl-spec) for the third-party dependencies bundled in the driver. Presently, it includes the C# wrapper libmongocrypt nuget package since we bundle the libmongocrypt library dlls in that package. This is used when generating/updating sbom.json with the third-party dependencies.
sbom.json - This file serves as the SBOM-lite, documenting the third-party dependencies bundled within the shipped driver. Its purpose is vital for DevProd, as it's required to furnish to Silk.
For now, generating/updating sbom.json is to be done manually every time we update our third-party dependencies.
> CSHARP-5070: Add SBOM file

- evergreen/evergreen.yml
Remove workaround to set open files limit for Macos-14-ARM hosts.
> CSHARP-5087: Bump MacOS version used for tests

- src/MongoDB.Driver/Linq/IMongoQueryProvider.cs
- src/MongoDB.Driver/Linq/IMongoQueryable.cs
- src/MongoDB.Driver/Linq/Linq2Implementation/MongoQueryProviderImpl.cs
- src/MongoDB.Driver/Linq/Linq2Implementation/MongoQueryableImpl.cs
- src/MongoDB.Driver/Linq/Linq2Implementation/Processors/Pipeline/PipelineBinder.cs
- src/MongoDB.Driver/Linq/Linq2Implementation/Processors/SerializationBinder.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/ExtensionMethods/ExpressionExtensions.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/MongoQuery.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToPipelineTranslators/ExpressionToPipelineTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToPipelineTranslators/UnionMethodToPipelineTranslator.cs
- src/MongoDB.Driver/Linq/MongoQueryable.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4684Tests.cs
This PR is to solve an issue Damien was having getting the `LoggedStages` in the EF Core Provider in some cases.
Our earlier work made `LoggedStage` available via the `IMongoQueryable` interface. But when executing "scalar" (single valued) LINQ queries the EF Core Provider calls `Execute` directly on the *internal* `IMongoQueryProvider`.
Damien was having to use reflection to call the `LoggedStages` property on the `IMongoQueryProvider`.
This PR is a proposal to make part of the `IMongoQueryProvider` interface *public* by splitting the interface into public and internal parts.
I also made the `ExecuteAsync` method public. Damien, you are already calling the `Execute` method (defined in `IQueryProvider`), do you not need to call `ExecuteAsync` to handle async queries? Or does EF Core not …
> CSHARP-4684: Make part of IMongoQueryProvider public.

- purls.txt
- sbom.json
- src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
- src/MongoDB.Driver/MongoDB.Driver.csproj
- tests/MongoDB.Driver.Tests/Packaging/PackagingTests.cs
Native crypto has been enabled in the libmongocrypt bindings: https://github.com/mongodb/libmongocrypt/pull/796.
A new release was done and this PR is just syncing the driver to that release and updating the sbom.json accordingly.
> CSHARP-4944: Update Libmongocrypt version and sbom lite

- src/MongoDB.Driver/Encryption/ExplicitEncryptionLibMongoCryptController.cs
- wrap uses of `RawBsonDocument` appropriately in using statements.
- Switch to using `BsonSerializer.Deserialize` in the `UnwrapValue` function instead of using `RawBsonDocument`. This helps us since we couldn't dispose of `RawBsonDocument` in this case as the returned value would be disposed as well. Also avoids us having to do cloning as a remedy if we were to still use `RawBsonDocument`.
Just want input on whether I'm missing something here by not using RawBsonDocument
> CSHARP-5065: Dispose RawBsonDocument in ExplicitEncryptionLibMongoCryptController.cs

- src/MongoDB.Driver/ProjectionDefinitionBuilder.cs
- tests/MongoDB.Driver.Tests/ProjectionDefinitionBuilderTests.cs
When fluently building a projection, each call to `Include` or `Exclude` creates a new `CombinedProjectionDefinition<T>` with the projection to that point and the new include/exclude projection. This results in a chain of nested projections. When this chain is rendered, `CombinedProjectionDefinition<T>.Render` is called recursively. With a large number of included/excluded fields, this can result in significant callstack depth. Although it is unlikely in common cases to overflow the stack, it is possible as demonstrated by the test case. This issue was resolved by flattening nested `CombinedProjectionDefinition<T>` instances.
> CSHARP-2187: Flatten CombinedProjectionDefinitions to reduce recursive calls to Render.

- src/MongoDB.Bson/Serialization/CollectionsSerializationProvider.cs
- src/MongoDB.Bson/Serialization/Serializers/MemorySerializer.cs
- src/MongoDB.Bson/Serialization/Serializers/PrimitivesArrayReader.cs
- src/MongoDB.Bson/Serialization/Serializers/PrimitivesArrayWriter.cs
- tests/BuildProps/Tests.Build.props
- tests/MongoDB.Bson.Tests/Serialization/Serializers/MemorySerializerTests.cs
This PR introduces custom fast serialization path for `Memory<T> `and `ReadOnlyMemory<T>`.
Deserializing `Memory`/`ReadOnlyMemory` is x4.5 times faster than regular arrays on .net8, and x7 faster on .net6.
The main performance gain is in the deserialization path, while the main serialization improvements are left out from this PR. 
Overflow and truncations checks are not implement yet, as the use-cases this scenario is optimized for exclude such need.
Deserialization performance results:
.net8
| Method               | Mean      | Error    | StdDev   |
|--------------------- |----------:|---------:|---------:|
| ArrayDecoding_int    | 379.96 ms | 6.854 ms | 6.076 ms |
| ArrayDecoding_float  | 385.77 ms | 4.181 ms | 3.911 ms |
| ArrayDecoding_double | 351.71 ms | 6.262 ms | 6.700 ms |
| …
> CSHARP-4807: Support serialization of Memory<T> and ReadOnlyMemory<T>

- specifications/command-logging-and-monitoring/tests/logging/unacknowledged-write.json
- specifications/command-logging-and-monitoring/tests/logging/unacknowledged-write.yml
- specifications/command-logging-and-monitoring/tests/monitoring/unacknowledgedBulkWrite.json
- specifications/command-logging-and-monitoring/tests/monitoring/unacknowledgedBulkWrite.yml
Note that this also addresses CSHARP-5020. The same two unified tests are updated by both tickets, and the latest version of these files includes both sets of changes.
> CSHARP-5120: Use single mongos in racy unacknowledged write tests.

- src/MongoDB.Driver/AggregateFluent.cs
- src/MongoDB.Driver/AggregateFluentBase.cs
- src/MongoDB.Driver/IAggregateFluent.cs
- src/MongoDB.Driver/PipelineDefinitionBuilder.cs
- src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
- tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
Added `$sample` stage to `Aggregate()`. Reorganized external PR, added some tests, and changed the `size` from `int` to `long`. The server accepts `NumberLong` for the `size` and throws on negative. Although the docs say that `size` must be a positive integer, empirical testing shows that zero is permissible and returns no documents as expected.
> CSHARP-2659: Adding support for $sample aggregation pipeline stage.

- tests/MongoDB.Driver.Tests/Jira/CSharp3397Tests.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
Found test that is duplicated with spec test "Aggregate with $out includes read preference for 5.0+ server" (defined in specifications\crud\tests\unified\aggregate-write-readPreference.yml)
> CSHARP-4017: Fix flaky Aggregate_with__out_includes_read_preference_for_5.0__server error

- src/MongoDB.Driver/Linq/Linq3Implementation/Misc/SerializationHelper.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/BinaryExpressionToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AbsMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/CeilingMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/DateTimeAddOrSubtractMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ExpMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FloorMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IndexOfAnyMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IndexOfMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/LogMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/PowMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/RangeMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/RoundMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/SqrtMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/SubstringMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/TruncateMethodToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegateExpressionToAggregationExpressionTranslator.cs
- src/MongoDB.Driver/Support/ReflectionExtensions.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4985Tests.cs
Let's not try and push this to master until after I get back. Feel free to take a look and comment. Mainly I wanted to get this work backed up.
I probably need a few more tests (though there are some tests already).
> CSHARP-4985: Verify that operands to numeric operators in LINQ expressions are represented as numbers on the server.

- src/MongoDB.Driver/ProjectionDefinition.cs
- src/MongoDB.Driver/ProjectionDefinitionBuilder.cs
- tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4681Tests.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5162Tests.cs
About a year ago we added `RenderForFind` and stopped using `FindExpressionProjectionDefinition`. That resulted in a subtle regression affecting LINQ2 that was only discovered relatively recently.
This PR fixes the regression by reverting back to using `FindExpressionProjectionDefinition` wherever it was used before, BUT then making `FindExpressionProjectionDefinition` behave the same as it used when using LINQ2 while behaving the SAME as `ExpressionProjectionDefinition` when using LINQ3.
The net effect is that when using LINQ2 everything works the same as it used to, and when using LINQ3 we have effectively (but not actually) replaced `FindExpressionProjectionDefinition` with `ExpressionProjectionDefinition`.
> CSHARP-5162: Continue to use FindExpressionProjectionDefinition to avoid regression against LINQ2

- evergreen/evergreen.yml
- specifications/client-side-encryption/tests/legacy/namedKMS.json
- specifications/client-side-encryption/tests/legacy/namedKMS.yml
- specifications/client-side-encryption/tests/unified/namedKMS-createDataKey.json
- specifications/client-side-encryption/tests/unified/namedKMS-createDataKey.yml
- specifications/client-side-encryption/tests/unified/namedKMS-explicit.json
- specifications/client-side-encryption/tests/unified/namedKMS-explicit.yml
- specifications/client-side-encryption/tests/unified/namedKMS-rewrapManyDataKey.json
- specifications/client-side-encryption/tests/unified/namedKMS-rewrapManyDataKey.yml
- tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedDecryptOperation.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEncryptOperation.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
This PR implements the changes described in the "Downstream Changes Summary" of [DRIVERS-2731](https://jira.mongodb.org/browse/DRIVERS-2731).
- Sync to new unified tests
- Implement required spec tests.
- Pass new AWS credentials to test a rewrapManyDataKey with two different AWS accounts using Evergreen expansions: FLE_AWS_NAMED2_ACCESS_KEY_ID and FLE_AWS_NAMED2_SECRET_ACCESS_KEY, configured in the Evergreen Variables page.
NOTE: No changes to the CSFLE API are necessary. All relevant logic is encapsulated within libmongocrypt.
Named KMS providers is further described in [DBX Scope: Support Named KMS Providers](https://docs.google.com/document/d/1IUxkgGFx5VLjMr7HWxBOXerN0pUZwcqWb11gLoRtcJs/edit?usp=sharing).
The KMS provider identified by a string. Previously supported KMS providers were …
> CSHARP-4892: CSFLE/QE Support for more than 1 KMS provider per type

- src/MongoDB.Driver/Core/Clusters/DnsMonitor.cs
When calling ComputeRescanDelay, there is a possibility that srvRecords is null so we should conditionally access it here.
> CSHARP-5252: Fix possible null reference

- evergreen/evergreen.yml
Introduced runtime_framework axe to use in smoke tests matrix to eliminate needs of copy-paste the myget dependency.
> Switch smoke tests to spec matrix

- src/MongoDB.Bson/Serialization/PrimitiveSerializationProvider.cs
- src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
- src/MongoDB.Bson/Serialization/Serializers/DateTimeSerializer.cs
- tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
- tests/MongoDB.Bson.Tests/Serialization/Serializers/DateTimeOffsetSerializerTests.cs
- tests/MongoDB.Bson.Tests/Serialization/Serializers/DateTimeSerializerTests.cs
This PR is still in draft because we need support for the .NET 6 target framework before merging. I have made the changes for .NET 6 locally, but I did not push them to avoid polluting the PR. 
The behaviour of `DateOnlySerializer` has taken mostly inspiration from `DateTimeSerializer` with `DateOnly = true`, including throwing an exception when deserializing a date time with a non-zero time component.
> CSHARP-5261: Add DateOnly support

- specifications/load-balancers/tests/sdam-error-handling.json
- specifications/load-balancers/tests/sdam-error-handling.yml
- specifications/server-discovery-and-monitoring/tests/unified/hello-command-error.json
- specifications/server-discovery-and-monitoring/tests/unified/hello-command-error.yml
- specifications/server-discovery-and-monitoring/tests/unified/hello-network-error.json
- specifications/server-discovery-and-monitoring/tests/unified/hello-network-error.yml
- specifications/server-discovery-and-monitoring/tests/unified/interruptInUse-pool-clear.json
- specifications/server-discovery-and-monitoring/tests/unified/interruptInUse-pool-clear.yml
- specifications/server-discovery-and-monitoring/tests/unified/minPoolSize-error.json
- specifications/server-discovery-and-monitoring/tests/unified/minPoolSize-error.yml
Sample previously skipped tests are now running and passing: https://spruce.mongodb.com/task/dot_net_driver_secure_tests_windows__version~4.4_os~windows_64_topology~sharded_cluster_auth~auth_ssl~ssl_test_net472_patch_8b465a2fb7c8b3cadf05729e38af910a659655df_67257c93ea33b9000738c24c_24_11_02_01_12_52?execution=0&page=0&sortBy=STATUS&sortDir=ASC&testname=hello-comman
> CSHARP-5061: Enable tests that require failCommand with appName on initial handshake before 4.9

- build.cake
- tests/MongoDB.Driver.Encryption.Tests/BasicTests.cs
- tests/MongoDB.Driver.Encryption.Tests/MongoDB.Driver.Encryption.Tests.csproj
Adds reference to test common properties file and some changes to address code warnings
> CSHARP-5402: Add missing reference for MongoDB.Driver.Encryption.Test project

- specifications/index-management/tests/createSearchIndex.json
- specifications/index-management/tests/createSearchIndex.yml
- specifications/index-management/tests/createSearchIndexes.json
- specifications/index-management/tests/createSearchIndexes.yml
- src/MongoDB.Driver/Core/Operations/CreateSearchIndexRequest.cs
- src/MongoDB.Driver/CreateSearchIndexModel.cs
- src/MongoDB.Driver/MongoCollectionImpl.cs
- src/MongoDB.Driver/Search/IMongoSearchIndexManager.cs
- src/MongoDB.Driver/SearchIndexType.cs
- tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateSearchIndexOperation.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateSearchIndexesOperation.cs
Add support for the `type` field when creating search indexes. Also syncs the unified search index tests and adds two new search index prose tests, as added in [jira.mongodb.org/browse/DRIVERS-2768](https://jira.mongodb.org/browse/DRIVERS-2768).
> CSHARP-4960: Add new type field support for search indexes

- src/MongoDB.Driver/Core/Operations/CursorBatchDeserializationHelper.cs
See [CSHARP-5412](https://jira.mongodb.org/browse/CSHARP-5412) for details.
This PR reuses a `BsonDeserializationContext` so that only one object needs to be allocated for a batch instead of one object per document in the batch.
> CSHARP-5412: Performance: Avoid allocations of BsonDeserializationContext when deserialising a batch

- src/MongoDB.Bson/ObjectModel/Decimal128.cs
See [CSHARP-5368](https://jira.mongodb.org/browse/CSHARP-5368) for details.
This PR removes allocations that happens for
- [`Enum.CompareTo(object? enum)`](https://learn.microsoft.com/de-de/dotnet/api/system.enum.compareto?view=net-8.0), because this results in boxing of both enums.
The alternative is `Comparer<T>.Default.Compar` for .NET 6.0 and manual int-casts for .NET 4.x.
- [`decimal.GetBits(decimal d)`](https://learn.microsoft.com/en-us/dotnet/api/system.decimal.getbits?view=net-8.0#system-decimal-getbits(system-decimal)) allocates an `int[4]` array on every call.
The alternative is [`decimal.GetBits(decimal d, Span<int> destination)`](https://learn.microsoft.com/en-us/dotnet/api/system.decimal.getbits?view=net-8.0#system-decimal-getbits(system-decimal-system-span((system-int32)))), …
> CSHARP-5368: Eliminiate allocations in Bson.Decimal128 to decimal conversion

- evergreen/evergreen.yml
- evergreen/sign-packages.sh
This commit templates our authenticode key name in preparation for the authenticode 2021 deprecation. The variable will be added to our Evergreen project as mongo-authenticode-2021, and later updated to 2024 when that certificate is ready.
> DEVPROD-13302: template authenticode key name

- evergreen/evergreen.yml
- evergreen/run-mongodb-oidc-env-tests.sh
- specifications/auth/tests/legacy/connection-string.json
- specifications/auth/tests/legacy/connection-string.yml
- src/MongoDB.Driver/Authentication/Oidc/FileOidcCallback.cs
- src/MongoDB.Driver/Authentication/Oidc/OidcCallbackAdapterFactory.cs
- src/MongoDB.Driver/Authentication/Oidc/OidcConfiguration.cs
- src/MongoDB.Driver/Authentication/Oidc/OidcSaslMechanism.cs
- src/MongoDB.Driver/Core/Misc/FileWrapper.cs
- tests/MongoDB.Driver.TestHelpers/Core/EnvironmentVariableProviderMock.cs
- tests/MongoDB.Driver.Tests/Authentication/Oidc/FileOidcCallbackTests.cs
- tests/MongoDB.Driver.Tests/ClientDocumentHelperTests.cs
- tests/MongoDB.Driver.Tests/Core/Connections/ClientDocumentHelperTests.cs
- tests/MongoDB.Driver.Tests/Core/Servers/ServerMonitorTests.cs
- tests/MongoDB.Driver.Tests/Specifications/auth/AuthTestRunner.cs
There are 2 separate commits that could be reviewed separately:
1) Implement EnvironmentVariableProviderMock - minor refactoring in tests for easier mocking of IEnvironmentVariableProvider
2) CSHARP-5026: Add Kubernetes Support for OIDC - implementation of the functionality itself.
> CSHARP-5026: Add Kubernetes Support for OIDC

- src/MongoDB.Bson/Serialization/Attributes/BsonDateOnlyOptionsAttribute.cs
- src/MongoDB.Bson/Serialization/IBsonSerializerExtensions.cs
- src/MongoDB.Bson/Serialization/Options/DateOnlyDocumentFormat.cs
- src/MongoDB.Bson/Serialization/SerializerConfigurator.cs
- src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
- src/MongoDB.Bson/Serialization/Serializers/SerializerHelper.cs
- tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
[JIRA ticket](https://jira.mongodb.org/browse/CSHARP-5345)
> CSHARP-5345: Unable to deserialize C# DateOnly objects

- CSharpDriver.sln
- benchmarks/MongoDB.Driver.Benchmarks/BenchmarkResult.cs
- benchmarks/MongoDB.Driver.Benchmarks/DriverBenchmarkCategory.cs
- benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/BulkWriteMixedOpsBenchmark.cs
- benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/LargeDocBulkInsertBenchmark.cs
- benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/SmallDocBulkInsertBenchmark.cs
- benchmarks/MongoDB.Driver.Benchmarks/README.md
- benchmarks/MongoDB.Driver.Benchmarks/scripts/download-data.sh
- evergreen/evergreen.yml
Here are results of the new benchmarks:
<markdown-accessiblity-table data-catalyst="" style="box-sizing: border-box; display: block; color: rgb(240, 246, 252); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Name | MB/sec
-- | -- …
> CSHARP-5203: Benchmark Collection and Client bulkWrite

- src/MongoDB.Bson/ObjectModel/BsonRegularExpression.cs
The `BsonRegularExpression(Regex)` constructor uses string concatenation to create the options string.
If there's none only one option, it will result on a static interned string. Otherwise, it will create new strings. One less than the number of options.
Using a buffer to create the string is only better when there are 4 options.
However, using precomputed strings (because they aren't that much) beat every option in time and memory consumption.
<details>
<summary>Benchmarks</summary>
```csharp
[HideColumns("Error", "StdDev", "RatioSD")]
public class RegexOptionsEnumToBsonRegularExpressionStringBenchmark
{
[Benchmark(Baseline = true)]
[Arguments(RegexOptions.None)]
[Arguments(RegexOptions.IgnoreCase)]
[Arguments(RegexOptions.IgnoreCase | RegexOptions.Multiline)] …
```
> Replace string creation with static strings for Regex options conversion to string

- evergreen/evergreen.yml
CRYPT_SHARED_LIB_PATH mandatory environment variable was recently added to EFCore test script. Have to mirror the changes here to make **test-efcore** task green in Driver's repo.
> CSHARP-5464: Fix EFCore tests

- specifications/load-balancers/tests/non-lb-connection-establishment.json
- specifications/load-balancers/tests/non-lb-connection-establishment.yml
Sync `non-lb-connection-establishment` test to https://github.com/mongodb/specifications/commit/d05c33e0a6124ee7d1a9de665084d540b2ff06c5
Intended to proactively avoid tests failure once drivers start testing 8.1 builds. See DRIVERS-3108. Drivers are not-yet testing 8.1 (see [slack](https://mongodb.slack.com/archives/C72LB5RPV/p1739884710850709)).
> CSHARP-5499 Sync `non-lb-connection-establishment` test

- specifications/load-balancers/tests/non-lb-connection-establishment.json
- specifications/load-balancers/tests/non-lb-connection-establishment.yml
Revert test skip from https://github.com/mongodb/mongo-csharp-driver/pull/1618
The server problem that initiated the test skip has been resolved so we can revert the skip and run the test on the latest server build.
> CSHARP-5514: Revert skip to non-lb-connection-establishment

- specifications/unified-test-format/tests/valid-fail/operator-matchAsDocument.json
- specifications/unified-test-format/tests/valid-fail/operator-matchAsDocument.yml
- specifications/unified-test-format/tests/valid-fail/operator-matchAsRoot.json
- specifications/unified-test-format/tests/valid-fail/operator-matchAsRoot.yml
- specifications/unified-test-format/tests/valid-pass/operator-lte.json
- specifications/unified-test-format/tests/valid-pass/operator-lte.yml
- specifications/unified-test-format/tests/valid-pass/operator-matchAsDocument.json
- specifications/unified-test-format/tests/valid-pass/operator-matchAsDocument.yml
- specifications/unified-test-format/tests/valid-pass/operator-matchAsRoot.json
- specifications/unified-test-format/tests/valid-pass/operator-matchAsRoot.yml
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
Also addresses [CSHARP-5534](https://jira.mongodb.org/browse/CSHARP-5534)
> CSHARP-5381: Add valid-pass and valid-fail tests for $$matchAsRoot and $$matchAsDocument operators

- tests/AtlasConnectivity.Tests/AtlasConnectivity.Tests.csproj
- tests/MongoDB.Bson.Tests/MongoDB.Bson.Tests.csproj
- tests/MongoDB.Driver.Encryption.Tests/MongoDB.Driver.Encryption.Tests.csproj
- tests/MongoDB.Driver.Examples/MongoDB.Driver.Examples.csproj
- tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
- tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
Tests were aborting with the following error on .NET 8 (especially on non-x86 platforms like s390x):
```
System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.TestPlatform.ObjectModel.Constants' 
threw an exception. ---> System.NotSupportedException: Specified method is not supported. at 
Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformEnvironment.get_Architecture()
```
This is caused by an outdated version of `Microsoft.NET.Test.Sdk` (e.g., `15.8.0`), which uses `PlatformEnvironment.get_Architecture()` — not supported on some platforms.
---
Upgraded `Microsoft.NET.Test.Sdk` to `17.13.0`, the latest stable release as of now, which includes:
- A fix for [`PlatformEnvironment.get_Architecture()` …
> CSHARP-5559: Update Microsoft.NET.Test.Sdk to 17.13.0 for s390x compatibility

- src/MongoDB.Bson/IO/BsonStreamAdapter.cs
See [CSHARP-5531](https://jira.mongodb.org/browse/CSHARP-5531) for details.
> CSHARP-5531:Reduce memory allocations in BsonStreamAdapter.WriteDouble and WriteInt64

- src/MongoDB.Driver/Linq/Linq3Implementation/Misc/Symbol.cs
- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionToFilterTranslator.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4535Tests.cs
If this approach looks good then I should still look for all places where a new `Symbol` is created and see if any other places need to wrap a `DowncastingSerializer` around a serializer for a derived type.
> CSHARP-4535: Support queries after casting IQueryable<Derived> to IQueryable<Base>.

- tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
Add new prose test from spec: https://specifications.readthedocs.io/en/latest/crud/tests/#16-generated-document-identifiers-are-the-first-field-in-their-document
> CSHARP-5370: Test driver-generated '_id' fields are first in documents

- tests/MongoDB.Driver.Tests/Specifications/sessions/SessionsProseTests.cs
It turns out we were already not gossiping cluster times in our monitoring connections. Our monitors send hello requests  which use a `NoCoreSession` instance when the wire protocol command is created for a hello request. A `NoCoreSession` instance has a null `ClusterTime` which cannot be changed and calling `session.AdvanceClusterTime` is also a no-op for a `NoCoreSession`. So this PR just adds the new prose test described in the Drivers spec update: https://github.com/mongodb/specifications/commit/b76cbf96807d96aa8ae4337a3f2b3c9be39d3487
> CSHARP-5204: Test Heartbeats don't gossip cluster time

- evergreen/evergreen.yml
The perf.send functionality in evergreen is no longer maintained and is not the preferred method of sending performance data to the signal processing service. This PR updates the evergreen yaml file to instead send the data down stream using the preferred performance-monitoring-api.corp.mongodb.com/raw_perf_results/cedar_report end point.
Changes were tested in [this patch](https://spruce.mongodb.com/version/681b77b8ddc9c60007e74f7c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
> DEVPROD-17449 - Replace perf.send with new direct end point for performance data submission

- build.cake
- build.ps1
- build.sh
- tests/AstrolabeWorkloadExecutor/AstrolabeWorkloadExecutor.csproj
- tests/AtlasConnectivity.Tests/AtlasConnectivity.Tests.csproj
- tests/BuildProps/Tests.Build.props
- tests/MongoDB.Bson.TestHelpers/MongoDB.Bson.TestHelpers.csproj
- tests/MongoDB.Bson.Tests/MongoDB.Bson.Tests.csproj
- tests/MongoDB.Driver.Encryption.Tests/MongoDB.Driver.Encryption.Tests.csproj
- tests/MongoDB.Driver.Encryption.Tests/xunit.runner.json
- tests/MongoDB.Driver.Examples/MongoDB.Driver.Examples.csproj
- tests/MongoDB.Driver.TestHelpers/MongoDB.Driver.TestHelpers.csproj
- tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
PR contains fixes for:
- run MongoDB.Driver.Encryption.Tests to run on net472 target (filter by test name to MongoDB.Driver.Encryption.Tests to see new tests run on net472 variants)
- remove installation of netcore 2.1 as we dropped support of netstandard2.0
- remove some leftovers in cake for Legacy Driver
- fix for Warning MSB3243 : No way to resolve conflict between "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "Microsoft.CSharp".
> CSHARP-5591: Configure MongoDB.Driver.Encryption.Tests to run on net472 target

- evergreen/evergreen.yml
More fixes related to the profile credentials changes to fix following variants:
[test-aws-lambda-deployed](https://spruce.mongodb.com/task/dot_net_driver_aws_lambda_tests_test_aws_lambda_deployed_patch_c2bec8127385cc76134e585d74454af35814ef07_683a1f8117c78c00072da11a_25_05_30_21_13_50?execution=0)
[atlas-data-lake-test](https://spruce.mongodb.com/task/dot_net_driver_atlas_data_lake_test_atlas_data_lake_test_patch_4ecb1797acf9f15b19a9b4dfa5f2ab5f40153ae9_683a1c781576680007a2671f_25_05_30_21_00_54?execution=0)
> CSHARP-5585: Remove reliance on Evergreen instance profile credentials

- src/MongoDB.Bson/Serialization/Serializers/PrimitivesArrayReader.cs
This PR fixes deserialization issues in PrimitivesArrayReader.cs which caused 51 test failures in the MongoDB.Bson.Tests suite on Big Endian systems (e.g., IBM s390x).
The deserialization logic relied on BitConverter.ToXxx(...) which assumes Little Endian memory layout. On Big Endian architectures, this results in incorrect values for arrays of primitive types such as Int64, Single, Double, and Decimal, leading to test failures.
- Replaced unsafe BitConverter usages with BinaryPrimitives.ReadXxxLittleEndian(...) for endian-safe reads.
- Covered conversions for:
-- float, double (via BitConverter.Int64BitsToDouble(...))
-- decimal (via Decimal128.FromIEEEBits(...))
-- char (casted from ushort)
-- All numeric types (e.g. int, long, ushort, etc.)
51 test failures resolved.
Example fixed …
> CSHARP-5614: Fix deserialization of primitive arrays on Big Endian systems

- src/MongoDB.Driver/Core/Clusters/Cluster.cs
- src/MongoDB.Driver/Core/Clusters/ServerSelectors/OperationsCountServerSelector.cs
- tests/MongoDB.Driver.Tests/Core/Jira/CSharp3173Tests.cs
- tests/MongoDB.Driver.Tests/Core/Jira/CSharp3302Tests.cs
- tests/MongoDB.Driver.Tests/Core/Logging/EventLoggerTests.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
This PR contains additional refactoring to Server Selection code, that is a part of Command Execution requirement. I've decided to have this as a separate PR to let more detailed review/investigation on the changes where and when we build list of connected servers used on Server Selection. The changes will let me easily capture both: selected server and server description that was used while the server selection, as we need that description to fulfill Command Execution requirements.
> CSHARP-5608: CSOT: Command Execution

- src/MongoDB.Bson/Serialization/BsonSerializer.cs
[CSHARP-5633](https://jira.mongodb.org/browse/CSHARP-5633)
> CSHARP-5633: BsonSerializer.IsTypeDiscriminated is not thread-safe

- src/MongoDB.Driver/BulkWriteInsertOneResult.cs
- src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
- src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
- src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
- tests/MongoDB.Driver.Tests/Jira/CSharp5697Tests.cs
- tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedClientBulkWriteOperation.cs
Cherry-pick of the changes in 3.4.x branch.
> CSHARP-5697: Fix Client.BulkWrite failure in case complex type is being used as Document's Id

- tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
- tests/MongoDB.Bson.Tests/Serialization/Serializers/TimeOnlySerializerTests.cs
- tests/MongoDB.Driver.Tests/Core/Operations/DistinctOperationTests.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
- tests/MongoDB.TestHelpers/XunitExtensions/ValuesAttribute.cs
Some tests have duplicated values in the Theory arguments. This leads to the warning like this:
```
[xUnit.net 00:00:11.08] MongoDB.Driver.Tests: Skipping test case with duplicate ID '2fb9bd387351a3fdf140e2605db341578e10eb73' ('MongoDB.Driver.Tests.Specifications.client_side_encryption.prose_tests.ClientEncryptionProseTests.RangeExplicitEncryptionTest(testCase: 1, rangeType: "DecimalNoPrecision", async: False)' and 'MongoDB.Driver.Tests.Specifications.client_side_encryption.prose_tests.ClientEncryptionProseTests.RangeExplicitEncryptionTest(testCase: 1, rangeType: "DecimalNoPrecision", async: False)')
```
> CSHARP-5710: Fix RangeExplicitEncryptionTest definition

- specifications/client-side-encryption/prose-tests/etc/data/encryptedFields-prefix-suffix.json
- specifications/client-side-encryption/prose-tests/etc/data/encryptedFields-substring.json
- src/MongoDB.Driver.Encryption/CryptClient.cs
- src/MongoDB.Driver.Encryption/EncryptOptions.cs
- src/MongoDB.Driver.Encryption/EncryptionAlgorithm.cs
- src/MongoDB.Driver.Encryption/EncryptionOptionsExtensions.cs
- src/MongoDB.Driver.Encryption/ExplicitEncryptionLibMongoCryptController.cs
- src/MongoDB.Driver.Encryption/LibmongocryptExtensionsMethods.cs
- src/MongoDB.Driver.Encryption/Library.cs
- src/MongoDB.Driver/Core/Misc/Feature.cs
- tests/MongoDB.Driver.Encryption.Tests/BasicTests.cs
- tests/MongoDB.Driver.Tests/Encryption/EncryptOptionsTests.cs
- tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
Added TextPreview support for Prefix/Suffix/Substring Indexes
> CSHARP-5625: Support text indexes for explicit encryption

- src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToExecutableQueryTranslators/AverageMethodToExecutableQueryTranslator.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AverageMethodToAggregationExpressionTranslatorTests.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/IntegrationTestBase.cs
- tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/MongoQueryableTests.cs
Fixes [CSHARP-5675: Average over empty collection of nullable types throws](https://jira.mongodb.org/browse/CSHARP-5675)
For the terminating operator, the fix is to use the SingleOrDefault finalizer when the type is nullable.
> CSHARP-5675: Where possible, return null for average over the empty set
